### ISSUE TITLE
Control with Win11 theming falls back to "old" theming when applying a style

### ISSUE THREAD

**Issue by Zagrthos** [dotnet/wpf#10054]
### Description

When applying a custom style to a control which is themed via the Windows 11 MergedDictionary it falls back to the old theming.

### Reproduction Steps

Create a new WPF Window and add a TabControl with TabItems to it. Then apply the following style to the window:
```
<Window.Resources>
    <Style TargetType="TabItem">
        <Setter Property="FontWeight" Value="Normal"/>
        <Style.Triggers>
            <Trigger Property="IsSelected" Value="True">
                <Setter Property="FontWeight" Value="Bold"/>
            </Trigger>
        </Style.Triggers>
    </Style>
</Window.Resources>
```

### Expected behavior

The style is just added without removing the theming.

### Actual behavior

Fallback to old theming
![Image](https://github.com/user-attachments/assets/3c9a0d80-5e38-42c8-8df2-62274259b11e)

### Configuration

* .NET Version: 9.0.100-rc.2.24474.11
* OS: Windows 11 22635.4445
* Arch: x64

### Other information

Maybe I am too new to WPF and that's expected, because it's wanted by design, but for me right now it's appears like a (possible) bug.

**Comment by dipeshmsft** [comment]
@Zagrthos, you are right. Since, you mentioned you are new, I will dig a little deep into this here.

All the FrameworkElements have two properties : `Style` and `ThemeStyle` . 
Before Fluent, for all the themes, the default control style was loaded in **ThemeStyle** property, leaving the **Style** property to be set by the user. In use cases like you have mentioned above ( where not all the properties are set in the custom style ), the remaining part of the style was picked up from style loaded in ThemeStyle property.

Fluent theme styles require more flexibility in terms of customizability and resource usage as compared to other themes, and so in the current system, the Fluent styles are loaded in the **Style** property. Whereas, Aero2 is still being loaded in the **ThemeStyle** property.

Now, when you provided your own style, the Fluent style got replaced and your style is being loaded in the FrameworkElement's **Style** property, and since only some of the properties are defined in the custom style rest of them are being picked from **ThemeStyle** ( i.e. Aero2 ) style.

To workaround this limitation, you can do the following : 

```xml
   <Style BasedOn="{StaticResource DefaultTabItemStyle}" TargetType="TabItem">
        <Setter Property="FontWeight" Value="Normal"/>
        <Style.Triggers>
            <Trigger Property="IsSelected" Value="True">
                <Setter Property="FontWeight" Value="Bold"/>
            </Trigger>
        </Style.Triggers>
    </Style>
```

**Comment by Zagrthos** [comment]
@dipeshmsft thanks for your kind explanation and the reply! I'm still trying to fiddle with WPF, tried it a few times already but XAML and MVVM scared me off a lot. Hopefully that'll work out now 😀

**Comment by aquinn39** [comment]
As a workaround, you can set BasedOn property of the Style to `{StaticResource DefaultCONTROLNAMEHEREstyle}`, but be aware that that will crash when the old themes are used.

**Comment by dipeshmsft** [comment]
@aquinn39 is right, initially I wrote that in my comment, but then it was pointed out by @harshit7962, that we missed giving a Key to TabItem style and then I removed that.

**Comment by dipeshmsft** [comment]
@Zagrthos, this has been fixed in both .NET 9 and the current development branch. I am closing this issue now. 

We have included the names for TabControl and TabItem style in the dictionary : `DefaultTabControlStyle` and `DefaultTabItemStyle` in the list of keys.
