### ISSUE TITLE
Remove 'IsWpfTempProject' workaround after .NET Core Preview 8 is released (Arcade #3129)

### ISSUE THREAD

**Issue by ryalanms** [dotnet/wpf#1055]
Tracking arcade issue: https://github.com/dotnet/arcade/pull/3129

WPF for .NET Core is adding a restore step to temporary project compilation for PackageReferences. The existing Arcade workaround needs to be temporarily updated to prevent duplicate imports, then removed entirely after the next WPF Preview release.

**Comment by ryalanms** [comment]
This depends on issue #811, which was moved to 5.0.

**Comment by vatsan-madhavan** [comment]
> This depends on issue #811, which was moved to 5.0.

a. We should ensure that the workaround we put into Arcade is completely benign and sustainable for the foreseeable future as part of this Issue - and if the answer turns out to be satisfactory, then we can move this issue to .NET 5. 

b. If the analysis is hard, time-consuming, discussion-prone, inconclusive, or otherwise unclear in any way, we should just roll-back the workaround from Arcade _now_. 

My suspicion is that this falls into category (a) very easily based on https://github.com/dotnet/arcade/commit/f63781e8073bda3b9124a7899ec054dde55826e4#diff-e678cb499f1aa47f14aca38f527f2598. Do you agree?
