### ISSUE TITLE
Update documentation for Default Items 

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/wpf#1302]
https://github.com/dotnet/wpf/issues/1264#issuecomment-512579451

> https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#default-compilation-includes-in-net-core-projects needs to be updated.

https://aka.ms/sdkimplicititems should be updated with information about `EnableDefaultPageItems` and `EnableDefaultApplicationDefinition` 

Also see https://github.com/dotnet/wpf/pull/1300

/cc @grubioe

**Comment by ryalanms** [comment]
These properties are used to determine if xaml files should automatically be added to Page and ApplicationDefinition items.

**Comment by grubioe** [comment]
@mairaw & @Thraka - is this something that you can help with (updating documentation)?

**Comment by Thraka** [comment]
Yes, can you file an issue in our repo? 

[Click here to create new issue linked to the article](https://github.com/dotnet/docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%20cb4428fc-215c-78e1-5ff0-fe73f7a08260%0A*%20Version%20Independent%20ID%3A%206741b1de-38a4-fbb1-d79d-acc47d549a2d%0A*%20Content%3A%20%5BAdditions%20to%20the%20csproj%20format%20for%20.NET%20Core%20-%20.NET%20Core%20CLI%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdotnet%2Fcore%2Ftools%2Fcsproj%23default-compilation-includes-in-net-core-projects)%0A*%20Content%20Source%3A%20%5Bdocs%2Fcore%2Ftools%2Fcsproj.md%5D(https%3A%2F%2Fgithub.com%2Fdotnet%2Fdocs%2Fblob%2Fmaster%2Fdocs%2Fcore%2Ftools%2Fcsproj.md)%0A*%20Product%3A%20**dotnet-core**%0A*%20Technology%3A%20**dotnet-cli**%0A*%20GitHub%20Login%3A%20%40mairaw%0A*%20Microsoft%20Alias%3A%20**mairaw**)

Please be clear in the issue as to what needs to change. Just browsing through the linked issues, it seems that this is a problem introduced in Core 3.0 Preview X and will be fixed in Core 3.0 Preview 7?

**Comment by Thraka** [comment]
Also, do you document all of the MSBuild options WPF projects use? Gathering this information would up tell the story correctly in our repo.

**Comment by vatsan-madhavan** [comment]
@grubioe, are these updates completed now?

**Comment by grubioe** [comment]
Being addressed by Docs issue #[13884](https://github.com/dotnet/docs/issues/13884)

**Comment by vatsan-madhavan** [comment]
Closing since it's being addressed

**Comment by grubioe** [comment]
Issue to address this is #[2642](https://github.com/dotnet/docs/issues/2642), ETA is November.
