### ISSUE TITLE
What is PBTCOMPILER? Is it redundant?

### ISSUE THREAD

**Issue by hughbe** [dotnet/wpf#140]
There are a lot of ifdefs for `PBTCOMPILER` in the codebase. Are these redundant? What does this check for?

**Comment by rladuca** [comment]
@hughbe Good question.  PBTCOMPILER is for PresentationBuildTasks.dll.  That DLL contains MarkupCompilerPass1/2 which are MSBuild tasks that build XAML.  That component is not yet released as open source, but shares some code with System.XAML.  The ifdefs are indeed needed.

**Comment by vatsan-madhavan** [comment]
Not redundant - it refers to PresentationBuuldTasks.dll’s main conditional compilation symbol. 

In general, avoid changing conditionally compiled code very much. There are some source files that had to be copied over to github while being maintained in the closed version separately because they are shared across multiple binaries. Over time we’ll end up with all sources in the same repo(github), but for now, we’d like to minimize coherency problems as much as possible - so we’d like to minimize (or avoid) churn to code blocks with conditional compilation (and to files with conditional compilation).

**Comment by hughbe** [comment]
Thanks for the quick response! Would be nice if we could document these ifdefs and hint they shouldn’t be removed m (If there’s never a plan to open source the library using it), or we can close this issue :)

**Comment by stevenbrix** [comment]
We defintely are planning on open sourcing the code very soon!
