### ISSUE TITLE
Feature: new WPF style for Windows 10

### ISSUE THREAD

**Issue by Berrysoft** [dotnet/wpf#1485]
The WPF style now used on Windows 10 doesn't match the legacy controls, which is created by WinForms. Here is a screenshot to compare some of them:

![image](https://user-images.githubusercontent.com/37586447/62183882-73245680-b38e-11e9-9975-84a097a38be2.png)

I suggest we should write a set of new style to match Windows 10 WinForms style, and also another new style for dark mode in Windows 10.

**Comment by mdtauk** [comment]
Maybe when a WPF app opts into the new WinUI 3.0 for Desktop - it could use the new styles coming with WinUI 3.0.

**Comment by weltkante** [comment]
How is WPF/WinUI interop going to work? Is WPF going to use the WinUI rendering engine? Otherwise I can't imagine a simple "opt in" working mixing classic WPF XAML with WinUI XAML in the same visual tree, they are different XAML dialects with different backing control classes, using incompatible APIs. People who want WPF XAML will still want up-to-date UI for their controls without having to port everything (in particular 3rd party controls) to WinUI.

**Comment by lindexi** [comment]
Do you means [UWP controls in desktop apps - Windows apps | Microsoft Docs](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/xaml-islands ) ?

**Comment by Berrysoft** [comment]
I agree with @weltkante . Although I could use WinUI, I still want up-to-date **WPF** style.

Now I write cross-platform programs with [Eto.Forms](https://github.com/picoe/Eto), which is a cross-platform GUI framework. It uses four backends on Windows - WinForms, DirectX, WPF and GTK# - but I prefer WPF. I can't use WinUI or WinRT Xaml because it is hard to embed them into an Eto.Forms program.

**Comment by weltkante** [comment]
@lindexi no he means the recently announced WinUI 3.0 which will have support for Desktop along the existing UWP. It will have better integration with WinForms/WPF than your linked UWP XAML Islands.

**Comment by mdtauk** [comment]
@weltkante  The Windows Shell is changing, so you would assume the Common Controls would also be updating.  If that is the case, then any changes to the standard WPF control templates, and the Win32 Common Controls, should probably be designed to match the style of the shell.

The shell is moving to XAML, so WinUI 3.0's control changes, would be leading the changes.

Why should the visual style not all match (even if the size of controls, font sizes, etc would differ)?

**Comment by weltkante** [comment]
@mdtauk maybe its a misunderstanding. I'm saying you can't just use the WinUI XAML in WPF due to the underlying technological difference, but you'd have to recreate the style on base of the WPF controls.

If you meant to recreate the "current" shell/common controls in WPF using WinUI as reference, thats fine with me.

What I'm against is telling WPF developers "just use the WinUI controls instead of the WPF ones and you get a modern style". They should have a modern style native to WPF.

(Note that at this point XAML is not a technology but a concept shared by multiple technologies in incompatible ways, so "the shell is moving to XAML" is very ambigous, unless you also say which dialect/technology of XAML you mean.)

**Comment by mdtauk** [comment]
@weltkante  As I understand it, when WinUI 3.0 comes out, XAML Islands will not be how you combine WinUI Xaml and WPF.  So you may have to compile your app with the latest SDK, before it will use any updated control designs.

Eitherway, WPF's control templates, should be refreshed alongside the WinUI Xaml controls, and the Win32 Common Controls - which should all take its lead from the Windows Design Team, and they follow Fluent Design.

**Comment by Shadowblitz16** [comment]
I think wpf should look native on classic, xp, vista, 7, and 8.

**Comment by Poopooracoocoo** [comment]
WPF looks really Windows 8-ey. I remember using Windows 8.1 and winforms looked like that too. I really hope Microsoft applies Fluent Design to all three but I don't see that happening especially as Microsoft both ditches and embraces UWP and still can't get consistency within Windows 10's UWP UI (like the system media controls).

**Comment by Poopooracoocoo** [comment]
uh. is this ever going to be seen

**Comment by Shadowblitz16** [comment]
in my opinion I think both winforms and wpf should looks the same and should use the proper rendering api's for each os.

this could also be made to work cross platform so that when and if wpf or winforms does go cross platform they can look native on max and linux

although I also think that the menustrip, toolstrip, and contextmenu strip should have done this a long time ago

**Comment by mdtauk** [comment]
WPF is closer to WinUI in the fact they use Xaml and have control templates.

Ideally there would be a Classic Theme - Winforms
and a Modern Theme - WinUI

So a WPF dev could pick which style they want.  The control metrics could be the same, with only the style changing

**Comment by Poopooracoocoo** [comment]
@Felix-Dev said:
>The WinUI team, which now owns WPF, said in the July Community Call that they plan to update the WPF styles for Fluent Design. They also said they would like to see the community helping them out with this so if this is a major concern for you, you might wanna help out here if possible.

:)

**Comment by Shadowblitz16** [comment]
I honestly think gui theming should not be in the hands of the developer
it should be in the hand of the user and should be consistent across all Microsoft gui frameworks.

this is part of the reason windows 10 has 6 different context menus

**Comment by jonasnordlund** [comment]
> I agree with @weltkante . Although I could use WinUI, I still want up-to-date **WPF** style.
> 
> Now I write cross-platform programs with [Eto.Forms](https://github.com/picoe/Eto), which is a cross-platform GUI framework. It uses four backends on Windows - WinForms, DirectX, WPF and GTK# - but I prefer WPF. I can't use WinUI or WinRT Xaml because it is hard to embed them into an Eto.Forms program.

I've looked around pretty hard for this myself and think this might be your best bet: https://github.com/Kinnara/ModernWpf

It's easy to migrate to and has ports of the WinUI controls for WPF. Note two things though:
1. There is an issue with using it in a class library project. (it has been reported)
2. It's still very much in active development which can be good and bad.

**Comment by ygoe** [comment]
WPF never really looked native after Windows 7. After a good theme for XP, they made such a great effort for Windows 7 (or was it Vista? can't remember that one), even including the animations that existed back then. Windows 8 had a slight gradient and soft border on the buttons when WPF only had that flat something of a box. Feels very unloved since then. And even more alien on Windows 10. I don't have Windows 11 but it seems to have moved on even further. WPF doesn't seem to be preferred technology anymore. But then, what is?

**Comment by optimus-code** [comment]
It's a shame WPF is a second-class citizen in the .NET ecosystem. MS keeps ignoring the huge demand for real desktop apps, WPF is a fantastic framework and is unrivalled in productivity - or was. It needs some love and attention, since .NET Core versions the built in themes are just broken.  There's inconsistencies everywhere and it's a huge shame. We need WPF to look native on all windows versions.

**Comment by echoix** [comment]
There's work already done for the Win 11 Fluent style in .NET 9 this November. Check the presentation videos at the build conference. (I'm only a user)
