### ISSUE TITLE
Fix bug where some tests require interaction to run

### ISSUE THREAD

**Issue by ojhad** [dotnet/wpf#1667]
When running the following tests on the following OSes, the tests get paused due to a popup warning that the publisher could not be verified. Selecting run resumes the tests and they pass.

OS: Win7 x86, Win7 x64, WinBlue x86, RS1 x86, 2K12R2 and RS1 ServerStandard

Tests:
![image](https://user-images.githubusercontent.com/6562139/63371462-01aa4900-c339-11e9-929e-f79361031919.png)

Popup:
![popup](https://user-images.githubusercontent.com/6562139/63371617-42a25d80-c339-11e9-9ad7-c9a69c79b5dd.png)

**Comment by rladuca** [comment]
This is due to NT Streams.  When we switched to building the test zip from the server, certain executables were marked with [zone identifiers](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/6e3f7352-d11c-4d76-8c39-2516a9df36e8).  This is causing them to be untrusted and require confirmation to run.  Some of these launch fine (DRTs, STI, QV itself) mainly due to launching from an admin cmd prompt instead of direct process execution.

I am looking at how to mirror this for various executables launched via ApplicationMonitor.

**Comment by rladuca** [comment]
Removing the zone identifiers from the zip file downloaded from the builds before extracting fixes this problem.  Waiting for confirmation before closure.

**Comment by rladuca** [comment]
Fixed by above.
