### ISSUE TITLE
Regression in application template, generic.xaml doesn't work out of the box

### ISSUE THREAD

**Issue by weltkante** [dotnet/wpf#1699]
* .NET Core Version: latest nightly (5.0.0-alpha1.19415.3)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 **Problem description:**
Creating a new WPF application for .NET Core the `generic.xaml` does not work out of the box when added manually (e.g. copy pasted from an existing project), it used to work on Desktop. It does work when using "new item" templates but since adding custom controls is just inheriting from a framework class it is often done without using the "new item" template and instead just writing code.
 
 **Actual behavior:**
Creating a new application with the WPF for .NET Core template does not add a ThemeInfo attribute, I need to add a CustomControl template to get the attribute. This is a regression from Desktop Framework template behavior.

 **Expected behavior:**
The WPF for .NET Core application template should already add the ThemeInfo attribute.
 
 **Minimal repro:**
* create a new WPF application for .NET Core
* manually add code for a Custom Control and generic.xaml

**Comment by weltkante** [comment]
Related issue #294 has been postponed to future, I want to point out above regression of the templates which can be confusing because `generic.xaml` doesn't work out of the box when writing code manually. You might want to consider updating the templates for 3.0, though its a minor issue and I can understand if it doesn't meet the bar at this point.

**Comment by ryalanms** [comment]
Discussed with @vatsan-madhavan: AssemblyInfo.cs with ThemeInfo should be added to the default WPF template.

**Comment by vatsan-madhavan** [comment]
@weltkante we will likely fix this in 3.1. 

If we already had an `AssemblyInfo.cs `for the [application template](https://github.com/dotnet/wpf/tree/master/packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp), we'd have taken this for 3.0. Adding a new `AssemblyInfo.cs` and wiring it up is easy, but it also means spending some time testing it to make sure that an innocuous error didn't creep in and break something else. Rather do this in 3.1. 

Since project templates can be consumed from a newer SDK while targeting netcoreapp3.0, and likewise VS can continue ingesting newer project templates while continuing to support netcoreapp3.0 targeting, this is not very critical to get in right-away.

**Comment by weltkante** [comment]
Seems like #1966 is fallout from this regression.

**Comment by vatsan-madhavan** [comment]
Application templates in .NET Core 3.1 and .NET Core 5.0 have been updated.
