### ISSUE TITLE
 [loc][Query][wpf] Localizability of 0; "ToStringFormatString_GridViewRowPresenter"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/wpf#1747]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
{0} The source code won't be available via Source Link.

File Name:
Strings.de.xlf

==========================================
Query:

Are these strings localizable? 
Several in scope:
{0} Columns.Count:\{1\}
{0} Header:\{1\}
{0} Content:\{1\} Columns.Count:\{2\}
{0} Header:\{1\} Content:\{2\}
{0} Header:\{1\} Items.Count:\{2\}
{0} Minimum:\{1\} Maximum:\{2\} Value:\{3\}
{0} Content:\{1\} IsChecked:\{2\}

Assuming that camel case words are not translatable, but can Content be localized, and can we insert punctuation?

**Comment by miloush** [comment]
They are all property values including `Content` so I wouldn't want to see them localized into my language when developing, so that I can refer back to code. If by punctuation you mean commas before spaces, then as long as you are not worried about any existing code parsing the strings manually, I don't see much problem with that.

**Comment by weltkante** [comment]
@miloush the localization team is probably not aware of any implementation details like parsing and are asking for an authoritative answer from a WPF team member, so general recommendations won't help much. Also they should prefer consistency, so saying not to localize a single language due to personal preference won't improve the general situation, it just makes things inconsistent.

If you want a general discussion you probably should open a separate issue.
