### ISSUE TITLE
[Question] Windows Platform Support

### ISSUE THREAD

**Issue by johannes-schmitt** [dotnet/wpf#183]
Which platforms will WPF support?

.NET Core 3 will support Windows 7, 8.1, 10 (1607+) and Windows Server 2012 R2 SP1+ (see [official announcement](https://blogs.msdn.microsoft.com/dotnet/2018/12/04/announcing-net-core-3-preview-1-and-open-sourcing-windows-desktop-frameworks/)), but does this also hold true for WPF?

**Comment by lindexi** [comment]
I run it in Windows 7,8.1,10

**Comment by johannes-schmitt** [comment]
Windows 7 SP1 support ends in January 2020. Will this affect WPF/.NET Core 3 also?

**Comment by lindexi** [comment]
A half of our users use Windows 7 and some of our users use Windows 7 without sp1.

**Comment by dotMorten** [comment]
.net core is supported past then, but if the issue is OS specific I don't see how it could be supported on Win7 after that, and I doubt any testing will be done, cleanup that breaks Win7 is likely etc. The products I'm working on that'll happen too and I'm assuming the rest of the industry will stop testing Win7 (testing is costly and developers are anxious to decrease testing scope).
Really you need to get your users upgraded. The clock is ticking (and get those people without the service pack updated immediately!)

**Comment by dotMorten** [comment]
Just don't upgrade to a version that doesn't support Win7 then and stick to 3.0. You had maaaany years to upgrade. At some point it has to stop.

**Comment by johannes-schmitt** [comment]
@rladuca the support matrix is for .NET Core 3.0, does it also apply for WPF? Obviously, it has to be a subset of what is supported by .NET Core 3.0, but not necessarily equal sets.

**Comment by rladuca** [comment]
@johannes-schmitt Yes, for WPF and WinForms only the Windows section applies.  

This matches the [supported OSes for the current released .NET Framework version (4.7.2)](https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements).  WPF customers that target .NET Framework 4.7.2 will not see a difference in supported OS version when porting to .NET Core 3.

**Comment by richlander** [comment]
> Windows 7 SP1 support ends in January 2020. Will this affect WPF/.NET Core 3 also?

We will support Windows 7 SP1 while it is supported by the Windows team. After support ends, we will also drop support. This applies to .NET Core 3 (and any later versions) as a whole. We don't intend on having different policies for WPF and Windows Forms, which is the basis of the question, I think.
