### ISSUE TITLE
Why does one of the DispatcherTimer ctors automatically start the timer?

### ISSUE THREAD

**Issue by lennartb-** [dotnet/wpf#2135]
Something I stumbled upon in one of our projects. If you use the `DispatcherTimer(TimeSpan interval, DispatcherPriority priority, EventHandler callback, Dispatcher dispatcher)` ctor, `Start()` is automatically called. However this is the only ctor that does that, for all others you need to explicitly call `Start()`. Was there any reason for that? 

This is the line in question:
https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/DispatcherTimer.cs#L97

**Comment by rladuca** [comment]
There is a missing code comment here that was likely cleaned during OSS prep.  The gist of it is that this constructor was added due to a request (in 2003) for a behavior that functioned more like `System.Threading.Timer`.  

I'd be hesitant to change this behavior seeing as it's been in WPF for a very long time (prior to the name of the class being `DispatcherTimer`).  We probably should file a documentation bug to more accurately describe this constructor though (and can update the comment on the constructor itself).

**Comment by BhaaLseN** [comment]
I reported this a while ago as dotnet/docs#3504, but it still doesn't seem to be documented.

**Comment by rladuca** [comment]
@BhaaLseN , thanks very much for filing that issue.  I know we haven't moved it along, but I just commented on it and we'll get the fixup to the docs in.  I'm going to close this and we'll track via that issue.
