### ISSUE TITLE
[Discussion/Cleanup] Can we remove ThreeValuedBool in favor of `bool?`

### ISSUE THREAD

**Issue by hughbe** [dotnet/wpf#218]
Simple really!

**Comment by stevenbrix** [comment]
The comment above the type definition seems to indicate that it serves a purpose. However, it looks like race conditions still exist with the way it used, since no one is doing any sort of interlock compare/exchange. In fact, the comment is misleading since it seems to imply that the type itself is thread-safe. Unless I'm overlooking something obvious, I don't see any reason why not.

**Comment by mikedn** [comment]
> However, it looks like race conditions still exist with the way it used, since no one is doing any sort of interlock compare/exchange. 

It doesn't need interlocked for that, at least not on x86/x64. But it does need the value to be atomic, something that nullable is not.

In general, if that code is truly used in a multithreaded manner such a change is not safe. Quite the opposite, you need to keep that enum and instead investigate adding volatile or interlocked so the code doesn't fail on ARM.

**Comment by weltkante** [comment]
@mikedn but isn't the JIT/CPU allowed to reorder instructions, even on x86/x64, if you don't use volatile or interlocked (or some other kind of barrier)?

**Comment by mikedn** [comment]
x86/x64 is pretty conservative in reordering loads and stores. You have a load, a store and then another load, all from the same location. Loads do not reorder, store followed by load to the same location does not reorder. So it seems like it should work fine.

If the value is atomic. Otherwise you have different locations involved and this means that some load/store reordering may occur.

The JIT is pretty conservative as well. It does load reordering and elimination but it cannot do this in this case due to the store (again, to the same location).

Of course, all this doesn't mean that not using volatile/interlocked is OK. They should be used, if only for the sake of clarity. Even on x86/64.

**Comment by stevenbrix** [comment]
@mikedn thanks for pointing that out, I just meant that some sort of barrier/synchronization is needed, volatile would also potentially work. All this is speculative and depends on how it's being used. From what I see, it seems to just be used as a replacement for nullable bool, and even if there was a race condition, I don't believe there would be any side effect since both threads would come to the same answer.

**Comment by stevenbrix** [comment]
thanks @mikedn for that little diagram, that makes. I had not thought about how Nullable actually stores values

**Comment by hughbe** [comment]
Closing per discussion :)
