### ISSUE TITLE
PresentationFramework.Aero not included by default when compiling against .NET Framework

### ISSUE THREAD

**Issue by livarcocc** [dotnet/wpf#219]
@twsouthwick commented on [Wed Nov 28 2018](https://github.com/dotnet/sdk/issues/2703)

I'm porting an app that relies on `PresentationFramework.Aero` for `ButtonChrome` and found I need to include the following in the csproj to get it to compile when building for .NET Framework 4.7.1:

```xml
  <ItemGroup Condition=" '$(TargetFramework)' == 'net471'">
    <Reference Include="PresentationFramework.Aero" />
  </ItemGroup
```

Is there a reason this isn't automatically included when setting `<UseWindowsForms>true</UseWindowsForms>`?

---

@livarcocc commented on [Wed Nov 28 2018](https://github.com/dotnet/sdk/issues/2703#issuecomment-442659308)

From talking to @rladuca it seems like this is not added by default for non-sdk based projects either. So, it seems like we are keeping with the current behavior.

Also, this is a WPF theme, so I am not sure how it relates to `UseWindowsForms` flag, as that is for WinForms and not WPF.

---

@rladuca commented on [Wed Nov 28 2018](https://github.com/dotnet/sdk/issues/2703#issuecomment-442660748)

That's correct, the set of binaries that are referenced when you make a new desktop framework WPF application do not include PresentationFramework.Aero.  This is also not referenced from a new Windows Forms application.

Adding the reference manually seems to be entirely appropriate.

@twsouthwick Are you saying that compiling for netcoreapp3.0 does automatically reference PresentationFramework.Aero?

---

@twsouthwick commented on [Wed Nov 28 2018](https://github.com/dotnet/sdk/issues/2703#issuecomment-442687337)

Sorry for the confusion - I meant `<UseWPF>true</UseWPF>`. The project has both of them and copied the first one I have.

@rladuca The project compiles fine for netcoreapp3.0, but now that I'm looking at it, it doesn't reference `PresentationFramework.Aero`. The file that references the aero library is here: https://github.com/twsouthwick/HandBrake/blob/netcore/win/CS/HandBrakeWPF/Themes/Generic.xaml.

**Comment by stevenbrix** [comment]
@livarcocc do we know if this is a WPF or MSBuild issue? Either way, I think there are two outcomes that lead me to believe that closing this as won't fix is the right outcome:

1. This has something to do with how we build WPF assemblies for .NET Framework, in which case we probably won't be fixing this (since the .NET Fx code doesn't live in this repo). This decision can be re-assessed if there is sufficient customer feedback that leads us to believe this is a serious issue.
2. This is an issue with the new SDK style MSBuild projects, in which case the issue should be moved to http://github.com/microsoft/msbuild so that it can be properly addressed and fixed by the MSBuild team.

Please respond if you feel strongly about this and we can re-open the issue and continue discussing futher, thanks!
