### ISSUE TITLE
MouseHover event not available

### ISSUE THREAD

**Issue by StormStark** [dotnet/wpf#2193]
I wanted change the default border color of the button and textbox when the mouse is hovering over the element.
Many websites show there is a MouseHover event present. I noticed there is a lot of mouse events (moseOver, mouseEnter, mouseLeave ,etc. ) presrnt but MouseHover.

Is there any other event that will do the trick?

**Comment by weltkante** [comment]
[TooltipService](https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/ToolTipService.cs)/[PopupControlService](https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/PopupControlService.cs) implement the hover pattern, I don't think there's anything besides tooltips requiring the hover pattern in the average Desktop application which is probably the reason its not exposed as event.

If you want to show a popup you can just use the tooltip functionality, otherwise you'll probably have to use 3rd party code or build the functionality you need by yourself, reacting on mouse events and starting a timer.

**Comment by miloush** [comment]
The `MouseHover` event is a Windows Forms event: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.mousehover. It is not available on WPF.

If you want to change a style for an element when mouse is over, use Style with `IsMouseOver` Trigger. See e.g. https://stackoverflow.com/questions/17259280/how-do-you-change-background-for-a-button-mouseover-in-wpf

If you really want to wait for a bit, another option to what @weltkante mentioned is to start an animation on the trigger.

**Comment by arpitmathur** [comment]
@StormStark: WPF doesn't have this event by design and there are no current plans to add it.
