### ISSUE TITLE
TreeView scroll issue

### ISSUE THREAD

**Issue by climbak** [dotnet/wpf#2302]
I encountered a strange scrolling issue in the WPF TreeView. I can only reproduce it with a specific layout and I have created a sample app to reproduce. I tried debugging the decompiled source in PresentationFramework, but was not able to find the true source.

The basics: I have a Grid layout in which I have put in a TreeView with some items in one column, a DataGrid in another column that shows details of the selected item in the TreeView. In the row below both the DataGrid and the TreeView, I have a button (I've tested a few different controls that all reprod) and it's in the same column as the DataGrid.

When the TreeView is scrolled down and an item is selected, the DataGrid populates with the details of the selected item and then an UpdateLayout is called on the TreeView which causes the ScrollInfo values on it's ScrollViewer to revert to a Y value of 0 and the TreeView scrolls to the top.

In my sample application, you can just run it, click the Fill button to add items then click Expand All to expand them. Scroll down a bit and select any leaf item and the TreeView will scroll back to the top.

If the button at the bottom is removed from the xaml or if the first Grid column that houses the TreeView is set to a set width or *, the errant scroll won't repro.

The sample project can be found here: https://github.com/climbak/TreeViewScrollingIssue

**Comment by SamBent** [comment]
This is a consequence of Grid's measure algorithm.  Your TreeView is in a grid cell with height=*, width=Auto -- a "Group2" cell, in the language of the comment in [Grid.MeasureOverride](https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Grid.cs#L459).  Grid measures such cells twice: once with infinite height, and once with the real height after resolving the *-rows.

Adding content to the DataGrid in column 2 provokes a measure of the Grid, which measures the TreeView with infinite height.  The TreeView de-virtualizes everything and resets its scroll offset to 0, since everything fits in an infinite viewport.  Later the Grid measures the TreeView with the real height (about 500px);  the TreeView re-virtualizes items that don't fit in the smaller viewport, but retains the scroll offset of 0.

This isn't fixable.  The TreeView doesn't know about Grid or "Group2" cells, so it doesn't know that the first measure is merely exploratory and can't do anything clever like remember the offset for the second measure.  Nor can Grid avoid the infinite-height measure (unless you're willing to provide a replacement implementation :).  And btw, the "scroll-to-top" behavior isn't the worst part of this;  try your repro with 100,000 items instead of only 100 or so, but be prepared to wait a _long_ time while they all get de-virtualized in the first measure.

The best guidance here is:  Don't put virtualizing controls where they can be asked to measure to infinite height.  Group2 grid cells are an example, admittedly not obvious.  Give the control an explicit height, or if you want the height to be set by an enclosing grid, avoid Auto columns.

**Comment by climbak** [comment]
I was afraid of something like that. I unfortunately have to use virtualization and I also need it to auto size, at least at first. I was able to put in a workaround to set the size explicitly after it's had a chance to autosize and before it can hit this behavior.

Thanks for the explanation.
