### ISSUE TITLE
CMYK Tif with transparency

### ISSUE THREAD

**Issue by EmaginationStore** [dotnet/wpf#2339]
* .NET Core Version: 3.1 & 3.0
* Windows version: 1903 (108362.239)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No 
 **Problem description:**
I have a tif image which is saved using CMYK colour space and contains transparency. 
If placed in an image control on a window, It shows in Visual Studio designer but does not show when debugging the app.
 
 **Actual behavior:** 
Image does not show
 
 **Expected behavior:**
The image to be visible
 
 **Minimal repro:**

```
<Window ...
    <Grid>
        <Image Source="Untitled-1.tif" />
    </Grid>
</Window>
```
tif attached in zip file
[Untitled-1.zip](https://github.com/dotnet/wpf/files/3983518/Untitled-1.zip)

**Comment by weltkante** [comment]
Please show the project file, I suspect you did not correctly add it to the project. You need to mark the image with a `<Resource>` tag for it to be included in the build.

It only works in the Designer because it picks it up from the filesystem relative to the project. If you copy the image to the output directory it may work just as well.

**Comment by EmaginationStore** [comment]
You are quite right, sorry it was not marked as a resource and now works.

So the behaviour in Visual studio differs between WPF for .net Framework and .net Core because when I import an image into a .net Framework WPF project, the image is automatically set as a resource, where .net Core is not.
