### ISSUE TITLE
A11y_VSUserStory935073-ContainerToolsWindow_ AddContainerOrchestratorSupport_ScreenReader:Narrator announces space unnecessarily for the "ok" button at the end.

### ISSUE THREAD

**Issue by gomathip02** [dotnet/wpf#2409]
Copied from VSO ID: 1029462

Bug Description:
“Check out Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier.” 

Environment Details:​
Application name-VS User Story 935073-Container Tools Window
Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.5.0 Preview 1.0 [29505.209.master]
OS: Win10

Repro Steps:​
1. Install and launch the Visual Studio2019 INT preview.
2. Create a project  after checking the "Enable Docker Support" checkbox under "Advanced label".
3. Right click on the "Project" created->click on "Add".
4. Select the "Container Orchestrator Support".
5. Start the Narrator.
6. Navigate to "ok" button.
7. Observe the narrator announcement.

Actual:
Narrator announces unnecessarily "space" for the "OK" button at the end.

Expected:
Narrator should not announces unnecessarily "space" for the "OK" button at the end.

This issue is not observed with NVDA.

User Impact:
Screen reader user does  get confused about the control.

Recommendations:​​
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx
​
MAS Reference:
MAS 1.3.1:
https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Comment by SamBent** [comment]
By design for WPF.  Narrator announces a control's AccessKey if it has one.  Setting Button.IsDefault=true sets the button's AccessKey to "\x0D" (ENTER).  Narrator chooses to announce this as "space".  That's Narrator's decision, Inspect shows the automation AccessKey property set correctly to \x0D.

WPF is exposing the AccessKey to automation correctly.
MAS Reference:   MAS 4.1.2:
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={248054a6-5e68-4771-9e1e-242fb5025730}
