### ISSUE TITLE
System.Diagnostics.Process.Start

### ISSUE THREAD

**Issue by OzBob** [dotnet/wpf#2566]
Goal: in a .netcore 3.1 WPF app, launch an external browser using a WPF Hyperlink NavigationUri property.

```
<Hyperlink NavigateUri="https://www.bing.com/" />
```

Does not work.

Extending the example and using MVVM:

XAML:
```
<Hyperlink 
    CommandParameter="{Binding NavigationUrl}" 
    Command="{Binding RequestNavigateCommand}"
    >ABN</Hyperlink>:
```

C#:
```
private void RequestNavigate(object obj)
        {
            if(obj is string destinationurl)
            {
                ProcessStartInfo sInfo = new ProcessStartInfo("start " + destinationurl);
                /*
                ProcessStartInfo sInfo = new ProcessStartInfo(destinationurl)
                {
                    //UseShellExecute = true,
                    UseShellExecute = false,
                    //Verb = "open"
                    Verb = "start"
                };
                 */
                Process.Start(sInfo);
            }
                //System.Diagnostics.Process.Start("msedge.exe",destinationurl);
                //System.Diagnostics.Process.Start("explorer.exe",destinationurl);
        }
```

Attempting all combinations of commented out lines Exception Message	

```
"The system cannot find the file specified."
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
```

Except when set UserShellExecute = true, then the warning is that it must be false to use "environment variables."

**Comment by OzBob** [comment]
A work around for this on windows: 

```
System.Diagnostics.Process.Start("cmd", "/C start" + " " + destinationurl);
```

**Comment by OzBob** [comment]
UWP allows for : 

```
await Windows.System.Launcher.LaunchUriAsync(uriBing);
```

https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-default-app

**Comment by weltkante** [comment]
.NET Core changed the semantics of `Process.Start` so any usage of it in WPF that expects the windows shell to be used needs to be updated to set `UseShellExecute=true` (note that setting this works both on Desktop and .NET Core). This is an intentional breaking change to allow the framework to align better with cross-platform code. (They had to take a breaking change to either previous .NET Core or Desktop Framework and preferred this one.)

see dotnet/runtime#28005 for the discussion

**Comment by OzBob** [comment]
When I change to

UseShellExecute = true

When running WPF app an exception is thrown not a warning. Saying 'UseShellExecute should be set to false' 

I'll run it again and get the exact msg...

**Comment by OzBob** [comment]
All good

The following code does a 'silent' browser open in windows: i.e. no command prompt 'flash'

```
 if(obj is string destinationurl)
            {
                var link = new Uri(destinationurl);
                var psi = new ProcessStartInfo
                {
                    FileName = "cmd",
                    WindowStyle = ProcessWindowStyle.Hidden,
                    UseShellExecute = false,
                    CreateNoWindow = true,
                    Arguments = $"/c start {link.AbsoluteUri}"
                };
                Process.Start(psi);
```

**Comment by OzBob** [comment]
note:
https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-prepare
says that if you intend to package your app for the appcentre/appstore, then it will fail certification if it has a CMD.exe task.


> Your application starts a utility to perform tasks. Avoid starting command utilities such as PowerShell and Cmd.exe. In fact, if users install your application onto a system that runs the Windows 10 S, then your application won’t be able to start them at all. This could block your application from submission to the Microsoft Store because all apps submitted to the Microsoft Store must be compatible with Windows 10 S.

> Starting a utility can often provide a convenient way to obtain information from the operating system, access the registry, or access system capabilities. However, you can use UWP APIs to accomplish these sorts of tasks instead. Those APIs are more performant because they don’t need a separate executable to run, but more importantly, they keep the application from reaching outside of the package. The app’s design stays consistent with the isolation, trust, and security that comes with an application that you've packaged, and your application will behave as expected on systems running Windows 10 S.

**Comment by weltkante** [comment]
Also note that opening URIs with cmd is just a workaround and not the recommended way to solve the problem, the recommended way is to use `UseShellExecute=true` (which in fact is what `/c start` command does, so you are just delegating the UseShellExecute to cmd.exe instead of doing it yourself)

If you are running into errors/bugs with `UseShellExecute=true` its still worth to look at the error and figure out what is going wrong.

**Comment by miloush** [comment]
I might be missing something, but what's wrong with `Process.Start("http://github.com/")`?

**Comment by weltkante** [comment]
@miloush It won't work on .NET Core because it will literally start the process with the executable `http://github.com/` (which is of course not a valid executable name in the file system).

In Desktop Framework because they have `UseShellExecute=true` as default for overloads which don't specify it explicitly. On .NET Core the default is false so you have to use an overload which allows you to specify it if you want Windows to resolve URLs and other fancy syntax.

But if you specify `UseShellExecute=true` to get the same behavior as Desktop Framework everything should work, if there are exceptions happening that would be something to investigate.

**Comment by rladuca** [comment]
@OzBob As @weltkante said, if you're seeing issues with `UseShellExecute=true` please file an issue on the https://github.com/dotnet/runtime.  They'll be better equipped to investigate and address any problems with `Process.Start`.

**Comment by OzBob** [comment]
To summarise: accepted WPF dotnetcore 3.1 solution for Hyperlink opening Windows OS default Browser with an URL:

````
            var destinationurl = "https://www.bing.com/";
            var sInfo = new System.Diagnostics.ProcessStartInfo(destinationurl)
            {
                UseShellExecute = true,
            };
            System.Diagnostics.Process.Start(sInfo);
````
