### ISSUE TITLE
Propagate bindings on ViewModel of UserControl

### ISSUE THREAD

**Issue by JenWilson82653** [dotnet/wpf#2596]
I have a UserControl that uses a ViewModel.  I want to be able to set a property on the ViewModel of the control and have the value propagate via bindings up to the ViewModel of the host page:

	<MainWindow DataContext="{Binding MainWindowViewModel}">
		<MyControl ViewModel="{Binding MyControlViewModel}" SelectedTabIndex="{Binding SelectedTabIndex}" />
	</MainWindow>

Both `MainWindowViewModel` and `MyControlViewModel` have a `SelectedTabIndex` property.  I want to change that property in a private method on `MyControlViewModel` and let the binding change in on `MainWindowViewModel`.

I created a very simple [working test harness](https://github.com/JenWilson82653/TabTest) that demonstrates the problem.

The only related question I could find on StackOverflow is [this one](https://stackoverflow.com/questions/22247633/binding-usercontrol-dependency-property-and-mvvm) which in my opinion does not provide a very useful answer (or perhaps I just don't understand it).

**Comment by weltkante** [comment]
Use `SetCurrentValue` instead of the property accessor, the property accessor (which will be using `SetValue`) discards the binding if there was any.

**Comment by JenWilson82653** [comment]
@weltkante 

       public int SelectedTabIndex
        {
            get { return (int)GetValue(SelectedTabIndexProperty); }
            set { SetCurrentValue(SelectedTabIndexProperty, value); }
        }

I also tried in the change callback:

    thisControl.SetCurrentValue(SelectedTabIndexProperty, e.NewValue);


Still not working sorry.

**Comment by weltkante** [comment]
No you are not supposed to use SetCurrentValue in the property accessor, that would break any external users of your control. SetCurrentValue is for your controls implementation.

For it to work someone must have bound to the control in the first place of course, and the bindings must be Mode=TwoWay (default for WPF, not for UWP). I'll have a look at your repo and submit a PR how to fix it. Otherwise feel free to search for SetCurrentValue examples/explanations because thats the API intended to write back values through bindings.

**Comment by JenWilson82653** [comment]
@weltkante Thank you.  I will research SetCurrentValue.

**Comment by weltkante** [comment]
Your problem is that your example repository makes no sense as far as your question is concerned, it is not testing what you are asking about:
- You have multiple ViewModel instances each with their own SelectedTabIndex variable but no code to sync them. Note that you cannot use WPF bindings to sync two ViewModels based on INotifyPropertyChanged, one side must be a DependencyProperty for WPF bindings to work. (Not that it matters, you didn't even try to sync the view models in xaml or code at all.)
- SetCurrentValue doesn't matter for your example at all because your command (on the button) is operating directly on the ViewModel, you don't have any code which wants to change SelectedTabProperty from within the control

I've made a PR adding a button to showcase usage of SetCurrentValue. Had to clean up your control implementation a bit:
- don't implement INotifyPropertyChange on controls, you inherit from DependencyObject and can (and should) use DependencyProperties
- use a Binding instead of implementing code to react on ViewModel changes

**Comment by weltkante** [comment]
If you were hoping to bind multiple ViewModels SelectedTabIndex agains the control to keep them in sync, thats not possible, WPF only can have one binding per property, you'd be replacing the previous binding if you tried that.

**Comment by weltkante** [comment]
I created another PR which is probably what you initially intended to do, manually having the control sync the ViewModel and the SelectedTabIndex. Like said above cannot be done in pure XAML because you can only have one binding per property. (So the SetBinding in the control constructor was redundant because it was getting overwritten anways.)

**Comment by JenWilson82653** [comment]
@weltkante Thanks for your PR, you've put me on the path to enlightenment.  BTW You didn't misread my question and I'm not trying anything magical.  I happen to have two instances of the child control in the example but I'm not trying to sync them.  I am only trying to do what the question says I'm trying to do.  Thanks again.

**Comment by weltkante** [comment]
The problem is that you were having multiple ViewModels with distinct SelectedTabIndex variables, which needs code to sync them. I hope you can work off these examples to find a way and figure out what you need.

**Comment by JenWilson82653** [comment]
After thinking about it for minute I guess you could say I'm trying to sync the control ViewModels - but not directly.  If they are in sync with MainWindowViewModel (my stated objective) they will be in sync with each other.
