### ISSUE TITLE
The border of ComboBox is not fully displayed in designer

### ISSUE THREAD

**Issue by Mandy1204** [dotnet/wpf#2712]
* .NET Core Version: 3.1.2
* Windows version: 19H2
* Does the bug reproduce also in WPF for .NET Framework 4.7.2: Yes

**Repro steps:**
1. Create a new WPF Core project.
2. Open toolbox, double click the ComboBox, you will see ComboBox shows normal in designer, xaml code like this: `<ComboBox x:Name=“comboBox” Width=“120”/>`
3. Selected the ComboBox, set attributes Height=“50” IsEditable=“True”, xaml code like this: `<ComboBox x:Name=“comboBox” Width=“120” Height=“50” IsEditable=“True”/>`
4. Observe the ComboBox, you will see part border of ComboBox will disappear. If you don’t see the border disappeared, please run the following steps.
5. F5-> type some character into the ComboBox->stop debugging ->Observe the ComboBox.

**Expected:**
ComboBox shows normal in designer.

**Actual:**
Part border of the ComboBox is missing unless you set your zooming at 100%
![image](https://user-images.githubusercontent.com/29625285/75955041-1377c600-5ef0-11ea-9304-15e0bfce18d1.png)

**Comment by rladuca** [comment]
@Mandy1204 You say this is an issue in the designer, but your image shows a running WPF application.  Can you clarify if the issue you are seeing is actually in the designer and, if so, provide a screenshot of that?

**Comment by miloush** [comment]
You can easily see the issue at runtime - the textbox and border are competing for screen pixels and I assume due to rounding one or the other wins (changes depending on the size of the window in this example). I would say if you want to make sure you see border at 0.5x size, make it BorderThickness="2"; otherwise the same way you could argue that you can't see anything at 0.001x size. However, it does feel like the framework could do a bit better at being consistent about which control wins.

I can see the same behaviour in the designer (not sure why it should be different).

**Comment by miloush** [comment]
You can see different parts of the border missing here, designer at 100%, 96dpi, same at runtime:

![image](https://user-images.githubusercontent.com/10546952/76029701-4e501d00-5f35-11ea-861b-8a788f8d5d03.png)
![image](https://user-images.githubusercontent.com/10546952/76029854-8d7e6e00-5f35-11ea-9e05-6ebce6db00aa.png)
