### ISSUE TITLE
Copy-wpf.ps1 file doesn't work as expected

### ISSUE THREAD

**Issue by Simon-IT** [dotnet/wpf#2726]
.NET Core Version: 3.1.200-preview-015002
Windows version: Windows 10.0.18363
Does the bug reproduce also in WPF for .NET Framework 4.8?: No
Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No

Managed and unmanaged files aren't copied due to the wrong source string directories.
For managed file :
- current string path: "...wpf\artifacts\packaging\Debug\Microsoft.DotNet.Wpf.GitHub\lib\netcoreapp5.0"
- right string path "...wpf\artifacts\packaging\Debug\Microsoft.DotNet.Wpf.GitHub.Debug\lib\netcoreapp5.0"

For unmanaged file:
- current string path: "...wpf\artifacts\packaging\Debug\Microsoft.DotNet.Wpf.GitHub.Debug\lib\win-x86"
- right string path ...wpf\artifacts\packaging\Debug\Microsoft.DotNet.Wpf.GitHub.Debug\runtimes\win-x86\native

CopyNativeBinariesToLocation, CopyManagedBinariesToLocation and CopyPackagedBinaries functions  should be modified

**Comment by Simon-IT** [comment]
@gomathip02 If you mark this issue as "up-for-grabs", I could implements a solution, that should be very simple

**Comment by vatsan-madhavan** [comment]
The layout of output folders under artifacts\ changes with some regularity, and corresponding upkeep of this script will require routine work [1].  There is also the fact that WPF team members - who would hope to benefit from such a script themselves as heavy users of the repo - would have to keep it working for two different repos ([dotnet/wpf](https://github.com/dotnet/wpf), and [dotnet-wpf-int](https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int) - the internal/private repo). 

There have been significant changes in the output structure between release/3.1 and .NET 5 (master) - largely owing to additional open-sourcing, but also due to reworking of how packaging works and the consequent layout generated in Debug vs. Release builds. Factoring in these changes and maintaining a single solution that _just works_ for the main use-cases seems like a significant effort. It can be done and there is much value in it that I can see, but IMO it should be in the realm of a "power toy" and not in that of a "supported repo/test script". 

A better architecture for this would be the generation of a "test-host" as part of the packaging process itself. By "test-host" I mean a test-version of .NET Core SDK that contains updated ref-pack assemblies and runtime assemblies (possibly with a synthetic version to avoid confusion). Producing a test-host that works for framework-dependent scenarios is relatively easy (self-contained scenario support is harder-to-implausible). That said, this (building a test-host as part of packaging) is the path I'd recommend forward, rather than continuing to maintain (or even retain) copy-wpf.ps1. 

[1] _I have much reason to make this claim - I have a [script](https://github.com/vatsan-madhavan/NetCoreScripts/tree/master/CopyWpfBins) similar to this  that I use for personal productivity that I maintain. It's often being edited while also being in use..._

**Comment by Simon-IT** [comment]
@vatsan-madhavan I completely agree. For external user like me, developer-guide.md file that should be a guide, is obsolete. For example, it refers to building _CoreFx_ project yet, while the correct project is _runtime_ instead. It could be very useful have a "project entry point" where it's well explained how to compile and debug WPF project
