### ISSUE TITLE
Runtime pack for Microsoft.WindowsDesktop.App should not include PDBs

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/wpf#296]
The "runtime pack" for Microsoft.WindowsDesktop.App" currently includes .pdb files.  These should not be included in this package.

**Comment by batzen** [comment]
Why shouldn't they be included?

**Comment by ericstj** [comment]
PDBs need to be in the private transport packages produced by WPF and WinForms packages.  That should not change.

PDBs should not be in the ref pack and runtime pack that are produced and downloaded by the SDK.
That is what this bug is talking about.  To make that change this line should be removed:
https://devdiv.visualstudio.com/DevDiv/_git/DotNet-Trusted/?path=%2Fpkg%2FMicrosoft.WindowsDesktop.App%2FMicrosoft.WindowsDesktop.App.pkgproj&version=GBmaster&line=17&lineStyle=plain&lineEnd=18&lineStartColumn=1&lineEndColumn=1

SymbolZips may be provided, similar to what is done for core-setup: https://github.com/dotnet/core-setup 
![image](https://user-images.githubusercontent.com/8918108/51925975-04e1e580-23a5-11e9-9442-08b6dad339ca.png)

Symbols should be published to the symbol servers so that they are accessible via http://symweb and https://msdl.microsoft.com/download/symbols.

**Comment by batzen** [comment]
> PDBs need to be in the private transport packages produced by WPF and WinForms packages. That should not change.

That doesn't answer my question to why they should not be included, aside from "that should not change" which is not a real answer.
Why is it bad to directly ship pdbs?

**Comment by ericstj** [comment]
PDBs still ship just not inside the runtime packs.  There's a separate story for acquiring PDBs because there is a separate story for using / consuming them.  I believe most of the arguments around not including them in the runtime packages is that its a bad cost/benefit balance.

The guidance from NuGet is to split symbols into a separate package: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/nuget#symbol-packages.  You then take the symbols and publish them to a symbol server, either the NuGet server, or in this case the microsoft public servers.  The debugger does a much better job of acquiring symbols when needed and caching them for its use.

That said, I think your suggestion is something that should be explicitly addressed in the spec for runtime packages.  That lives over here: https://github.com/dotnet/designs/pull/50/files  Would you mind taking this discussion to that spec?

**Comment by ericstj** [comment]
Also "that should not change" was meant to indicate that this repo is doing the right thing in including its pdbs in its private transport packages that it produces, not that we shouldn't question status quo.  I'm sorry if it sounded like I was dismissing your comment, that wasn't my intent.

In the case of the transport packages we need the PDBs inside because they are consumed by another repository that cross-gen's the binaries and rewrites the PDBs, similar to [what is done in core-setup](https://github.com/dotnet/core-setup/blob/988132f2a89decd7203d665d26df53bc1c8f9eec/src/pkg/projects/Microsoft.NETCore.App/src/Microsoft.NETCore.App.depproj#L286-L314).

**Comment by zsd4yr** [comment]
@dsplaisted I think you're good to close this issue now 😄  https://devdiv.visualstudio.com/DevDiv/_git/DotNet-Trusted/pullrequest/161647?_a=overview

**Comment by stevenbrix** [comment]
Closing per discussion, thanks everyone!
