### ISSUE TITLE
Provide GetMatrixCurrentValue for DrawingContext

### ISSUE THREAD

**Issue by skarllot** [dotnet/wpf#2993]
Would be nice to retrieve the current matrix value for a `DrawingContext`, as the `Transform` property from `System.Drawing.Graphics` does.

**Comment by weltkante** [comment]
could you elaborate? normally there is no "current transform" since DrawingContext just records drawing calls and they can be executed with arbitrary outer transforms

Do you mean retrieving the relative combined transform over previous PushTransform calls? They'd only have limited use and not allow any conclusions about the actual transform when the drawing is evaluated.

**Comment by skarllot** [comment]
I have an abstraction over `DrawingContext`, `SKCanvas` and `System.Drawing.Graphics` and I have 4 transform methods: `ClearTransform`, `PushTransform`, `PushResetTransform` and `PopTransform`.
The problem is to implement the method `PushResetTransform`, because I need to retrieve the combined transform invert it and push the result.

**Comment by nsivov** [comment]
You can probably accumulate resulting transform in your wrapper instead.

**Comment by skarllot** [comment]
@nsivov yes, I can and I actually doing that. But this leads to duplicating matrix computation, one in my wrapper and other in `DrawingContext`.

**Comment by weltkante** [comment]
> But this leads to duplicating matrix computation, one in my wrapper and other in DrawingContext.

If this is true then its probably an implementation detail, I don't think `PushTransform` needs to compute the matrix multiplication immediately. Its been a few years since I studied the DC implementations in reference source but as far as I remember the API design allows for creating structured records for later optimization or playback, multiplication of transforms can be deferred to native code for example.

That doesn't prevent having an API to retrieve the aggregate transform, but it may be more costly than you expect.

Personally I prefer it if DC consumers that actually need a transform would be specifying their required transforms explicitly being passed as arguments, then the caller can respect the visual tree (if he desires) and actually provide a true inverse to pixel resolution instead of an partial inverse without any meaning.

Just my opinion and reasons, not saying retrieving the transform is a bad thing by itself, just that it can more easily lead to writing bad code.
