### ISSUE TITLE
Make it possible for WPF datagrid to bind to a 2D array

### ISSUE THREAD

**Issue by Markz878** [dotnet/wpf#302]
Please make it possible for WPF datagrid to bind directly to a multidimensional 2D array of primitives. There are already some packages for this, but would be nice to get this obvious feature automatically.

**Comment by bigworld12** [comment]
a raw 2D array won't work, it doesn't support binding because it doesn't raise events when items change, you would need a nested `ObservableCollection<ObservableCollection<T>>` for this to work
so the actual request should be support Dynamic binding of columns when the row is of type `ObservableCollection<T>`

**Comment by weltkante** [comment]
Binding is more than updating on changes, so the request has some value if you just want to bind for display. Though its not exactly hard to write a container around a 2D array which implements the necessary interfaces, so its more of a convenience than actually enabling new scenarios.

**Comment by stevenbrix** [comment]
@weltkante do you just want a one time bind for this scenario? Also, do you know if this scenario works using x:Bind in a UWP project?

**Comment by weltkante** [comment]
I don't think Binding/x:Bind is the right place to implement that support, and I don't think the issue creator meant that either. He probably just wants to put a 2d array into a datagrid and have a way to configure columns against it. So its more like a control-specific implementation.

Since grids need a row identity (they are based on ItemsControl) you would have to create a wrapper class around the 2d array, because natively you can't reference a row in a 2d array. You would have to bind the columns against the rows of this wrapper. There is precedent of how binding columns against an object array looks so I probably would model the wrapper rows according to the binding syntax of an object array. (Technically you probably could even create object arrays for the rows, but that would involve the memory overhead of a complete copy of the 2d array; a wrapper row could get away with just indexing into the 2d array instead of copying every row.)

Personally I'm not terribly worried about having this feature in the framework, just wanted to step in and say its not technically impossible/unreasonable. Like I said its pretty easy to write a wrapper yourself, I have been doing that in winforms for years (implemented IBindingList wrappers around 2d arrays and other things) and I believe thats compatible with WPF even though I didn't use it there yet. I'm not the original creator of the issue though, so he might have other arguments why its important for him to have this feature directly in the framework instead of referencing a third party library.

**Comment by weltkante** [comment]
Taking a step back, I cannot determine if WPF actually fully supports IBindingList/ITypedList. I thought it was added in some update but cannot find the docs for it, so maybe it was just partial support. I never had to implement gridviews in WPF so far, still using WinForms for that, sorry.

If WPF only supports the IList part of IBindingList, and not the custom column definitions of ITypedList which you can have in WinForms, it might be more worth adding support for that than special casing just for 2d arrays. Not sure if we are going off topic here and should be splitting off into a separate issue, though.

**Comment by weltkante** [comment]
I have prototyped what I believe should be an appropriate wrapper around a 2d array to enable datagrid binding. Like I said, not hard, apparently WPF mostly honors IBindingList/ITypedList, with the exception that it ignores the GetValue/SetValue of the PropertyDescriptor when they look like indexers. Easily worked around by adding an actual indexer though.

https://gist.github.com/weltkante/e4a616d629e09cf88b25aaf7864080c2

As said before I'm not the original creator of the issue, so I don't know his arguments why such a wrapper should be automatically applied by the datagrid. I'm fine with the current state of writing my own and just wanted to show that its not hard to do.
