### ISSUE TITLE
PI is the abbreviation for ???

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/wpf#3213]
I found there's a PIMapping, so I want to PI is the abbreviation for ???

**Comment by miloush** [comment]
Processing Instruction

**Comment by miloush** [comment]
Sorry, I feel like I haven't given my best to this answer. The `Mapping` XML processing instruction was used in early builds of WPF to reference assemblies before the current `xmlns:x` system.

For more information, see e.g. 2) in [February CTP of WinFX Published -- Breaking Changes](https://docs.microsoft.com/en-us/archive/blogs/karstenj/february-ctp-of-winfx-published-breaking-changes), or Charles Petzold's [Accessing Non-XAML Assemblies in XAML](http://www.charlespetzold.com/blog/2006/02/231059.html).

In the source code, [XamlTypeMapper.AddMappingProcessingInstruction](https://github.com/dotnet/wpf/blob/0a3e920ee767024ff14c50077d6d04eafddce59f/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlTypeMapper.cs#L137) might be of interest to you.

**Comment by CreateAndInject** [comment]
Thanks, by the way, what's the meaning of `XmlnsProperty.AssemblyIds`?

**Comment by miloush** [comment]
There is no `XmlnsProperty.AssemblyIds` as far as I can see in the WPF code. If you mean `BamlXmlnsPropertyRecord.AssemblyIds`, then that is a set of indices into the `BamlMapTable.AssemblyIdMap` for `xmlns` definitions that correspond to the given assembly. In BAML, assemblies are only referenced by a number to save space and time.

What are you working on?

**Comment by CreateAndInject** [comment]
I can't understand.

```
AssemblyInfo [AssemblyId=0x0000, AssemblyFullName="MyAsm, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"]
PIMapping [XmlNamespace="clr-namespace:Test", ClrNamespace="Test", AssemblyId=0x0000]
XmlnsProperty [Prefix="local", XmlNamespace="clr-namespace:Test", AssemblyIds={0x0002, 0x0003, 0x0005}]
```
For `local:Demo`: It meant there's a type `Test.Demo` in the assembly `MyAsm`
In the past, I think `PIMapping.AssemblyId` must be one of `XmlnsProperty.AssemblyIds`, but I found not.
So, why we need AssemblyIds? We can find the type `Test.Demo` in assembly `MyAsm` by `local->clr-namespace:Test->Test (AssemblyId=0)` without AssemblyIds.

**Comment by miloush** [comment]
A XML namespace can correspond to several CLR namespaces. The `AssembleIds` of `XmlnsProperty` record lists all assemblies that have mapping to the XML namespace.

For example, in assembly A1 being the WPF app, you will have:
```C#
[assembly:XmlnsDefinition("http://test.com", "NamespaceA1")]
```
in assembly A2 that the WPF app references, there will be
```C#
[assembly:XmlnsDefinition("http://test.com", "NamespaceA2")]
```

Then `xmlns:a="http://test.com"` in your WPF app will correspond to a `XmlnsProperty` record with both A1 and A2 in the `AssemblyIds` list, so that the parser knows both assemblies need to be checked when resolving the type of e.g. `<a:Class1 />` element.

**Comment by CreateAndInject** [comment]
Create a WPF app `MyWpf` by vs2019
```
<Window x:Class="MyWpf.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:MyWpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        
    </Grid>
</Window>
```
Build it without any chanages.
View the output in dnSpy
```
DocumentStart [LoadAsync=false, MaxAsyncRecords=0xffffffff, DebugBaml=true]
	AssemblyInfo [AssemblyId=0x0000, AssemblyFullName="MyWpf, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"]
	PIMapping [XmlNamespace="clr-namespace:MyWpf", ClrNamespace="MyWpf", AssemblyId=0x0000]
	LineNumberAndPosition [LineNumber=0x00000006, LinePosition=0x00000009]
	TypeInfo [TypeId=0x0000, AssemblyId=0x0000, TypeFullName="MyWpf.MainWindow"]
	ElementStart [TypeId=0x0000, Flags=0x00]
		AssemblyInfo [AssemblyId=0x0001, AssemblyFullName="PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"]
		AssemblyInfo [AssemblyId=0x0002, AssemblyFullName="WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"]
		AssemblyInfo [AssemblyId=0x0003, AssemblyFullName="PresentationCore, Version=4.0.0.0, Culture=neutral, 
		AssemblyInfo [AssemblyId=0x0004, AssemblyFullName="System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"]
                 ......................
		XmlnsProperty [Prefix="local", XmlNamespace="clr-namespace:MyWpf", AssemblyIds={0x0004, 0x0001, 0x0002, 0x0003}]
```

Note:
```XmlnsProperty [Prefix="local", XmlNamespace="clr-namespace:MyWpf", AssemblyIds={0x0004, 0x0001, 0x0002, 0x0003}]```

The namespace `MyWpf` is defined in ourself project only, and doesn't exist in System assembly(PresentationFramework, WindowsBase, PresentationCore, System.Xaml), so why does AssemblyIds contains these 4 assemblies?

**Comment by miloush** [comment]
What you will also note is that if you move the `xmlns:local="clr-namespace:MyWpf"` line above all other namespace declarations, it will have empty `AssemblyIds`.

What happens is that the BAML records are cached by type during writing. If the `xmlns` attribute contains "traditional" (e.g. `http://`) namespace, the `AssemblyIds` are populated from the attributes like I described above. If the namespaces are `clr-namespace:`, no mapping is needed and the `AssemblyIds` is not set. The consequences of _not set_ is that if you receive an instance of the `BamlXmlnsPropertyRecord` from the cache rather than create a new one, `AssemblyIds` is left as it was when it was last used, effectively carrying the `AssemblyIds` from the previous `xmlns` attribute with traditional namespace.

When the BAML is read, the `AssemblyIds` values are [only checked](https://github.com/dotnet/wpf/blob/ae1790531c3b993b56eba8b1f0dd395a3ed7de75/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/Baml2006Reader.cs#L2142) if the namespace is not `clr-namespace`, so it does not slow down type resolving. The only thing that could be improved is to save around 8 bytes in the file.

**Comment by CreateAndInject** [comment]
Thanks!
