### ISSUE TITLE
Why MouseDown event doesn't work for LMB?

### ISSUE THREAD

**Issue by Alvin-Seville** [dotnet/wpf#3271]
Why MouseDown event [doesn't work](https://drive.google.com/file/d/1ONQRPYDmLzhqyrIqiDbxXIO3OJopWPru/view?usp=sharing) for LMB? When I click my button via LMB nothing happens but everything works as expected for MMB and RMB.

**Comment by miloush** [comment]
The critical information here is that the affected element is a _button_.

This is by design. The `Button` handles the event itself to fire the `Click` event when appropriate. If you want to handle the `MouseLeftButtonDown`, use the preview event as [documented](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.button?view=netcore-3.1#remarks).

**Comment by ryalanms** [comment]
Thanks, @miloush.  @Alvin-Seville, thanks for opening the issue.  Please reactivate if the answer is insufficient.
