### ISSUE TITLE
"The Name 'XXX' has already been defined" build error occurs if ControlTemplate has visual element and VisualState with the same names 

### ISSUE THREAD

**Issue by pavelovcharov** [dotnet/wpf#350]
* .NET Core Version: 3.0.100-preview-010184
* Windows version: 1809 (17763.253)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 
 
 **Problem description:**
Build error occurs if ControlTemplate contains a visual element and VisualState with the same names

 **Actual behavior:** 
Build error "MC4101: The Name 'Normal' has already been defined. Names must be unique." occurs

 **Expected behavior:**
No build errors
 
 **Minimal repro:**
Create new .Net Core 3 wpf project, add the following ControlTemplate
```
    <Window.Resources>
        <ControlTemplate TargetType="Button" x:Key="buttonStyle">
            <Border x:Name="Normal">
                <VisualStateManager.VisualStateGroups>
                    <VisualStateGroup x:Name="TestGroup">
                        <VisualState x:Name="Normal" />
                    </VisualStateGroup>
                </VisualStateManager.VisualStateGroups>
            </Border>
        </ControlTemplate>
    </Window.Resources>

```
and try to build the project.

**Comment by stevenbrix** [comment]
Thanks @pavelovcharov for filing this issue! This is interesting, in a .NET Framework WPF app, you see an intellisense error, and an error shows up in the ErrorsList, but doesn't cause your build to error. The UWP Xaml Compiler also treats this as an error condition as well, and your build will fail. However, I don't imagine there is any technical reason for this, as these names should never cause a collision.

@ryalanms i'm assigning this to you. i'd imagine we should make sure this doesn't cause errors so that porting from .NET Framework -> .NET Core is as easy as possible. however, we should continue having discussions so that these behaviors are consistent and both UWP and WPF behave the same

**Comment by ryalanms** [comment]
This difference was due to a bug in BamlMapTable.

**Comment by weltkante** [comment]
@ryalanms This doesn't look like a bugfix, if the same code works in Desktop Framework it should not be necessary to reinitialize static properties on every instance creation.

Note that your "fix" broke thread safety (see comment on PR)

Either make it threadsafe (probably will be a performance loss because you need a lot more locking now) or look for the real difference between .NET Core and Desktop Framework. The static initialization wasn't the difference.
