### ISSUE TITLE
Binding doesn't update when DataContext changes if overridden Object.Equals is true

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#3558]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/608757/binding-doesnt-update-when-datacontext-changes-if.html)._

---
<p>There is a bug in BindingExpression.OnDataContextChanged when the DataContext object overrides Object.Equals and the new context 'equals' the old one. The call to Object.Equals(DataItem, newItem) should be Object.ReferenceEquals(DataItem, newItem). See the attached example project.</p> <p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/78912-bindingbug.zip">bindingbug.zip</a></p>

---
#### Feedback Bot on 6/17/2019, 00:29 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/8/2019, 09:33 AM: 

We want to let you know that this problem will likely be closed in 60 days. We set priority based on severity, similar reports, and the overall impact on users and scenarios. We've also learned that reports without fresh activity could indicate that the problem isn't a problem anymore. One of our goals is to give you more transparency around these decisions as resolving every problem that gets reported isn't always possible. Your feedback is essential for helping us decide what needs the most attention, so please keep upvoting and commenting if you think that we need to make this a higher priority .

---
### Original Solutions
(no solutions)

**Comment by gab** [comment]
I ran into this as well, and hope it can be fixed, the current behavior can be pretty surprising. Using ReferenceEquals just makes more sense in this context.

**Comment by miloush** [comment]
The current behavior seems by design & correct to me, if the new object is equal to the old object, then there is no need to re-evaluate the bindings.

**Comment by gab** [comment]
Sorry, I disagree. It's a trap that has been messing with people's expectations since at least 2007 https://kent-boogaart.com/blog/beware-datacontext-and-equals-overrides. Most people expect everything to refresh if the Datacontext is replaced by a completely different object, it's widely understood to have reference semantics not value semantics.

(I'd have to double-check but I think that the DataContextChanged event doesn't fire either if Equals() return true, which will wreck havoc on your code if you need to update your own references.)

Overall business objects can have a good reason to implement Equals() a certain way in their context, for instance it could mean that objects are "interchangeable" but not fully equal. The same logic doesn't necessarily apply for display purposes, and having to box a business object just to ensure a WPF-side refresh is obnoxious.
 
OTOH I can't think of a use case where checking Equals() instead of ReferenceEquals() would be a useful performance improvement. Let the business logic use it's own Equals() before requesting to change the Datacontext for those 0.001% of cases.

**Comment by miloush** [comment]
The method is called `Equals` not `IsInterchangeableWith`. Your argument works both ways: add your own method to indicate whether objects are "interchangeable". Note that it's not only data binding that is affected, it's dictionaries, sorting etc., overriding `Equals` is a pretty serious claim in .NET.

I don't see evidence for "most people" and "widely understood", but even if that was the case, it doesn't make such behaviour correct. It doesn't even sound logical, first you would easily get into infinite binding loops and second, value types such as integers would suddenly become unequal to themselves.

Either way, while we might disagree, changing the current behaviour would be a serious breaking change.

**Comment by SamBent** [comment]
Calling Object.Equals is correct, using reference equality instead would be wrong.

Object.Equals determines whether two objects are fully equal, in the sense that they yield identical behavior in _all_ situations.  It extends "equality" to cases where reference equality doesn't make sense (value types), and to cases where reference equality isn't strong enough (reference types with "value semantics", like System.String).  You should not override Object.Equals to mean something weaker like "interchangeable in a certain way in their [the business object's] context", as this breaks the contract that .NET and WPF relies on in dozens of places, including this one and the ones mentioned by @miloush. 

In the attached repro, the app overrides Object.Equals to depend on only one aspect of the object (its MyString property), then uses the object in a situation that depends on other aspects (its PropertyChanged event).  It's the app's bug, for breaking the Object.Equals contract.

WPF and .NET use Object.Equals instead of reference equality in all those places because they have to handle all objects (not just reference types), and because they should honor correctly-implemented "value-semantics".  For this particular usage, @miloush mentions some other good reasons, to which I'll add perf.  Changing DataContext is potentially very expensive, as it involves propagating the new value down the tree to elements that inherit, and often rebuilding (or replacing) entire subtrees.  We don't have to do any of that if the objects are fully equal.

**Comment by gab** [comment]
Alright, I yield. Thanks for the thorough explanation, both of you. The use cases I had seen seemed legit from the limited point of view of the applications they were being used for, but your explanation of the big picture makes a lot of sense.

I can't help but wonder how to help people avoid what seems to be a common trap though. Perhaps the fact that Objet.Equals is used for comparing the DataContext should be clearly documented? It might appear obvious to you, but it's definitely not obvious for multiple people out there (cf blog post I linked, and those I know personally).
