### ISSUE TITLE
UIElement.Arrange invades other row or column in a grid.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#363]
I put an UIElement in a grid row 1. When I arrange it with any size and without point, it moves to row 0. When I put a border in the grid and put an UIElement in the border, it doesn't happen. The container seems to prevent the abnormal moving of the UIElement.

Please do this simple code. The TextBlock1 is in row 1 of grid.

TextBlock1.Arrange(new Rect(new Size(100, 100)));

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/461892/uielementarrange-invades-other-row-or-column-in-a.html
VSTS ticketId: 796027_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by thomasclaudiushuber** [comment]
I think this is the expected behavior. 

The Arrange method arranges an element within it's parent container. If you have it in the Grid and you call it without position, it will be at the top left. If you put it in a Border, it will be at the top left of the Border.

I think this is not an issue, it is the expected behavior.

The next point is that you shouldn't call the Arrange method on an element if you don't build a container like a Decorator or a Panel. Only these elements call arrange in a layout pass to arrange the elements. This happens after calling the Measure method on the elements.

**Comment by thomasclaudiushuber** [comment]
I think this is the expected behavior.

The Arrange method arranges an element within it's parent container. If you have it in the Grid and you call it without position, it will be at the top left. If you put it in a Border, it will be at the top left of the Border.

But I wonder why you call the Arrange method on that element? What's the reason? If you don't build a container like a Decorator or a Panel it might not be necessary. Or what is your use case? Normally only parent elements call arrange on their direct children in a layout pass to arrange their child elements. This happens after calling the Measure method on the child elements.

**Comment by dotMorten** [comment]
Agree. You're really not meant to call arrange and measure on elements unless you're building your own subclass of Panel.

**Comment by stevenbrix** [comment]
I've also tried to reproduce this behavior given the information provided, and I'm not really seeing any issues. Hopefully the original filer of this issue can provide more information if this is believed to be a true product issue.
