### ISSUE TITLE
wpf error when using process.mainwindowhandle

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#369]
hello

when i have in wpf window (first app)

 protected override void OnStateChanged(EventArgs e)
        {
            base.OnStateChanged(e);
            if (this.WindowState == WindowState.Minimized)
                this.ShowInTaskbar = false;
            else if (this.WindowState == WindowState.Maximized)
                this.ShowInTaskbar = true;
        }

if another application (second app)
i use process.mainwindowhandle the hwnd is correct

if in first app i reduce window
in the second app process.mainwindowhandle is zero

i chekc with spy++ and the window exist
findwindow return the good hwnd

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/463863/wpf-error-when-using-processmainwindowhandle.html
VSTS ticketId: 796705_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by stevenbrix** [comment]
See documentation on the `Process.MainWindowHandle` API here: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.mainwindowhandle?view=netcore-3.0

This looks like it is by design, and is also not directly an issue with WPF. If the issue is with the design of the API, this issue should be filed in the https://github.com/dotnet/corefx repo.
