### ISSUE TITLE
Binding should respond when any property changes?

### ISSUE THREAD

**Issue by suprak** [dotnet/wpf#3810]
Trying to understand how to achieve a binding (with a converter) to update whenever any property on a `DataContext` object changes.

Example,
```xaml
<Button DataContext="some complex object that implements INotifyPropertyChanged">
   <TextBlock Text={Binding Converter=...} />
</Button>
```
The complex type accurately sends `PropertyChanged` events, but since the inner Binding does not specify a Path, no updates are triggered.

Is this expected behavior?
Is there a better/proper way of achieving this?

(We have tried triggering a PropertyChanged event for `string.Empty`/`null`, but that only works for updating Bindings that are bound to a specific property/Path of a complex object)

**Comment by SamBent** [comment]
This is expected behavior.  There's no way to ask a binding to listen to all property changes from a given source.  Such a feature would be simple enough to implement, but hard to justify as it encourages useless runtime work.

Your TextBlock's Text doesn't actually depend on all the properties of the source, but only on the ones queried by the converter.  The proper way to do this is with a MultiBinding whose child bindings mention the desired properties, and whose converter combines them the way you want:
```
<TextBlock>
  <TextBlock.Text>
     <MultiBinding Converter="...">
        <Binding Path="Property1"/>
        <Binding Path="Property2"/>
        <Binding Path="Property3"/>
     </MultiBinding>
  </TextBlock.Text>
</TextBlock>
```
This is better than the "all properties" approach, especially when your source object changes values of properties that aren't relevant to this text.  (Running your converter in this case is the "useless runtime work" mentioned earlier.)

Another common approach is for the source object to do popular conversions, exposing the result as a separate property.  The standard example is a Rectangle that exposes "basic" properties named Top, Left, Height and Width, and "computed" properties named Bottom and Right (computed as Top+Height, Left+Width).  Now you can replace a MultiBinding to Top and Height with a 
Binding to Bottom.
