### ISSUE TITLE
Survey: Repo contribution experience, Fall 2020

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/wpf#3829]
We normally focus on how to improve the product, but we’re also turning our focus to improving the open source project. Periodically we are running a survey to collect feedback on your experience working with our repos. We did one back in May, and as its been about 6 months, its about time for another. We’ve created a survey to better understand your individual experience of participating and contributing in this project.

We would appreciate your feedback so we can work to address shortcomings and missed opportunities. 

Survey

Thank you for your time!

**Comment by Symbai** [comment]
The overall experience here is pretty much explained by this randomly picked PR: https://github.com/dotnet/wpf/pull/1169 more than a year and a half and literally NO feedback. And this PR added only a single line of code, so it isn't complex or anything that could explain why the maintainers here would need that much time to say "yay" or "nay" or even "hi & bye". Really, I'm not sure what else to say.

I did this survey and the survey before but I don't see anything has changed from last survey and if it needs a third survey to see the issues, then I'll likely spend my time otherwise. No offense.

**Comment by ClosetBugSlayer** [comment]
I feel like Microsoft has a political reason that they aren't sharing with us, to stonewall any future WPF development. Look at the check-in history for the whole repo. I don't think anyone on the WPF team understands anything about WPF and I think that's on purpose. I can't believe I have to explain airspace to them. This has been going on for almost a whole decade.

Until I have reason to believe otherwise. I keep an open mind but I am an engineer who has no time for fantasies.

I think one of us benevolent dictators is going to eventually fork WPF and be serious and generous about it, and then you won't have to worry about us anymore. Thank you so much for open sourcing it. That was really all you had to do.

**Comment by Symbai** [comment]
Meanwhile, Winforms received some great improvements: https://devblogs.microsoft.com/dotnet/whats-new-in-windows-forms-runtime-in-net-5-0/ and WPF? Well... think for yourselves.

**Comment by samsp-msft** [comment]
The survey is now closed. Thank you to everyone who provided feedback. I have removed the link from the first post.
