### ISSUE TITLE
Lack of templates for creating new WPF items (Page, ResourceDictionary, Window, etc)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#387]
VSF_TYPE_MARKDOWNHello. I can't add new wpf page on wpf application.
please help me

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/471000/wpf-app-bug.html
VSTS ticketId: 802964_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by stevenbrix** [comment]
This sounds frustrating, but some more information is needed:

1. Version of .net sdk installed (output of running `dotnet --version` from console) 
2. Version of Visual Studio being used
3. Operating system version

One thing i noticed when trying to add a new UserControl is that there was an error popup about referencing "System", however it seemed to work fine. However, i have a feeling this bug is about the lack of default templates when you go Project->Add->New Item->WPF. VS currently only shows UserControl on .NET Core, whereas on .NET Fx there are many other options (one of them being page)

**Comment by stevenbrix** [comment]
@richlander can you confirm the resolution here? I believe this is a VS issue

**Comment by poqut** [comment]
- .NET Core Version: 3.0.100-preview5-011568
- VS 2019 Preview 3
- Windows 10 1809

On [Preview 3 Release Notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#netsdk-tools) it states:

- Context menu item support for WinForms on .NET Core (#137): Windows Form, User Control, Component, and Class.
- Context menu item support for WPF on .NET Core (#137): Window, Page, User Control, Resource Dictionary.

Even all Winforms items are available on Add Item dialog, they don't appear at that context menu. And WPF still have only UserControl on Add Item dialog.

So I thought that they even added support for that menu, maybe it's related with WPF that it doesn't trigger something on VS to show them in dialog and also menu.

I'm a newbie and sorry if I'm writing this to the wrong place, I've just wanted to inform.
