### ISSUE TITLE
DragDrop with TextBox no longer sets data type to StringFormat

### ISSUE THREAD

**Issue by adegeo** [dotnet/wpf#3965]
The code from the .NET Framework WPF walkthrough about drag-drop, it doesn't work on .NET 5/Core 3.1: https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control?view=netframeworkdesktop-4.8

Specifically it's this check:

```csharp
if (e.Data.GetDataPresent(DataFormats.StringFormat))
```

In .NET Framework the drag-drop operation is initiated from a textbox creates a the data object of type `DataFormats.StringFormat`.

In .NET 5/Core 3.1, the data object generated is `DataFormats.Text`

Reported in dotnet/docs-desktop#160

**Comment by ryalanms** [comment]
@adegeo:  Thank you for the report.

**Comment by adegeo** [comment]
@ryalanms I just had another report of this in the docs repo. I used .NET 6 Preview 4 and the bug still exists.

**Comment by adegeo** [comment]
Tagging @einarstokke and @rubend30 for notifications

**Comment by jestrickler90** [comment]
This is still an issue in .NET 6.

**Comment by miloush** [comment]
This is happening because of https://github.com/dotnet/wpf/commit/875b508196b1c69bf930ee676ee9aa5d594c32f7:

![image](https://user-images.githubusercontent.com/10546952/189530604-99f837c9-e9e5-44c9-9090-8215556f91ab.png)

The last parameter, `autoConvert` is `true` by default on .NET Framework (except for `DataFormats.ApplicationTrust`):

https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Documents/TextEditorCopyPaste.cs,822

This almost looks like an oversight during the broad commit to me, since users can get `SystemFormat` from `Clipboard.GetDataObject().GetFormats()` after setting string even in .NET Core.

That said, the documentation could probably be changed to just use `UnicodeText`.
