### ISSUE TITLE
Build error: PropertyChangedEventManager does not exist

### ISSUE THREAD

**Issue by omghb** [dotnet/wpf#401]
* .NET Core Version: 3.0.100-preview4-010476
* Windows version: 1809
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 **Problem description:**
I tried to port a .NET Framework / WPF application to .NET Core 3. Build output:
Error	CS0103	The name 'PropertyChangedEventManager' does not exist in the current context

The [PropertyChangedEventManager](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.propertychangedeventmanager?view=netframework-4.7.2) is important for us to prevent memory leaks. WPF Binding internally uses it as well.

Will this class be available in .NET Core 3.0 / WPF?

**Comment by omghb** [comment]
This was an error on my side. I forgot to change `<Project Sdk="Microsoft.NET.Sdk">` to `<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">`.

**Comment by NinjaCross** [comment]
@omghb could you please explain how you solved your problem ?
I changed the project sdk as you suggested, but I still cannot find the class PropertyChangedEventManager in any of the dependent packages, nor in other packages I installed (i.e. Microsoft.Windows.Compatibility, System.ComponentModel, etc).
It seems it only exists in WindowsBase.dll, which I cannot reference since it only available for NET Framework, not for NET CORE

**Comment by weltkante** [comment]
besides changing the SDK you also need to add <UseWPF>true</UseWPF> in the properties section (because both WinForms and WPF are in the same SDK you need to opt-in to which you want to use)

**Comment by NinjaCross** [comment]
> besides changing the SDK you also need to add `<UseWPF>true</UseWPF>` in the properties section (because both WinForms and WPF are in the same SDK you need to opt-in to which you want to use)

Thank you very much @weltkante, this solved the problem
