### ISSUE TITLE
[PMA] Image in data tip scale wrongly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#404]
VSF_TYPE_MARKDOWNVS version : 28704.21.d16.0stg

1. Create a WPF project, add a button to it.
2. Set a break point in code behind xaml, debug the project
3. Hover over variable &quot;mybutton&quot; [See attached screenshot]

Actually
Image in the data tip too big in my 100% scale monitor

More info
In my 200% scale monitor, the image size is correct.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/476876/pma-image-in-data-tip-scale-wrongly.html
VSTS ticketId: 807933_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by stevenbrix** [comment]
I don't see any attachments in the linked issue. But this sounds like an issue in Visual Studio displaying variables, and isn't related to the running application.  If this is incorrect, please re-open this issue and provide more information.

**Comment by weltkante** [comment]
@stevenbrix I'm a bit worried about the practice of @vsfeedback moving random VSTS developer community tickets over to this WPF repo where they are closed as "not WPF related" or "neds more info" even though they more likely are VS bugs. Since they are also closed on the developer community side nobody will look at these now. The correct action would be to move them back or reopen them on developercommunity. Not sure if thats even possible. In either way someone should probably bring it to the attention of some responsible people on the developer community side.
