### ISSUE TITLE
Remove WPF's workaround for Arcade setting _WpfTempProjectNuGetFilePathNoExt

### ISSUE THREAD

**Issue by ryalanms** [dotnet/wpf#4119]

**Comment by tydunkel** [comment]
Just discovered that this was causing issues in our build. Adding this to the GlobalProperties resulted in out WPF projects rebuilding dependent assemblies, copying the original output from obj to bin. After copying to bin our build signs the assembly, so at that point an unsigned assembly replaced a signed assembly.

We build projects in parallel, so some projects depending on the original project are building but will be taking an unsigned version of the assembly until the newly copied assembly is signed. This resulted in build failures since some assemblies are unsigned in our nupkgs.

To fix this, we just added `_WpfTempProjectNuGetFilePathNoExt` to `GlobalPropertiesToRemove` when we build WPF projects. Easy workaround, but took awhile to figure out which property was causing the rebuild.
