### ISSUE TITLE
Why did you create VisualTreeHelper class?

### ISSUE THREAD

**Issue by zwcloud** [dotnet/wpf#478]
Dear WPF devs, this is a question about the thoughts and considerations about the API `VisualTreeHelper`.

A [StackOverflow answer](https://stackoverflow.com/a/2205934/3427520) by @paulcbetts said:

> I believe it is intentionally obfuscated a bit, because you shouldn't be directly fiddling with the visual tree most of the time, fitting with the "Framework Design Guidelines" philosophy of "Commonly used classes should follow basic scenarios".
> Since any method in Visual would be on pretty much any WPF control, they chose to put these advanced methods in a separate class. What the Framework designers are subtly trying to tell you is, "You shouldn't use this function unless you really know there's no better way to do what you're doing".

That sounds quite reasonable. And I would like to know original ideas from WPF devs.

**Comment by weltkante** [comment]
I doubt you'll find many original devs here after more than 12 years since the release, but maybe you are lucky.

While your quoted response does make some sense, a important technical reason is that they want to support multiple distinct subclass hierarchies. For example Visual and Visual3D don't have a common subclass, similar things happen between FrameworkElement and FrameworkContentElement (not with VisualTreeHelper but the situation is similar). Internally they just juggle multiple variables, probably for performance, but for the public API it makes a lot of sense to expose static helper methods to make it more discoverable and user friendly.

It also helps people fall into the "pit of success", when writing code most people wouldn't even think of testing Visual3D (or FrameworkContentElement) code paths, so if you directly cast to Visual or FrameworkElement and use the properties on it, you can run into problems when someone puts a Visual3D or FCE in your tree.

**Comment by stevenbrix** [comment]
@zwcloud unfortunately @weltkante is right right that there aren't many original WPF devs here. I think both the answer on Stack Overflow and what @weltkante added on are correct. I'm fairly confident this was intentional and had a good reason, unfortunately what that exactly was is lost to the sands of time. In general, when an API is under discussion we tend to think about the specific use case for it is. If that use case is common enough, then it is something that probably should be exposed on the type.  More advanced/niche scenarios would probably lend themselves to being exposed by a static helper class.  So in that respect the obfuscation is intentional as you quoted above, since we want to lead people on the path to success, and not overwhelm them with APIs that are only intended for more advanced scenarios. Of course we are only human and may have gotten this wrong at times. 

There are also times where we simply cannot add an API without taking into consideration pre-existing ones.  An anecodtal example (I'm unsure if this is what really happened) would be the VisualTreeHelper.GetParent() API.  This API will return the visual parent of the element passed in, and not the logical parent that is returned by FrameworkElement.Parent.  It would not have been wise if we added a FrameworkElement.VisualParent property since this probably would cause more confusion.

I know it's not exactly what you were looking for, but hopefully this helps answer your question?

**Comment by stevenbrix** [comment]
I'm going to close this issue for now, but please re-open if you still have some unanswered questions.
