### ISSUE TITLE
Open Source?  Where's the source?

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/wpf#496]
Where's the source for WPF?   According to this article:
https://www.hanselman.com/blog/AnnouncingWPFWinFormsAndWinUIAreGoingOpenSource.aspx

WPF is going open soruce but I can't seem to find the code anywhere.

**Comment by jespersh** [comment]
It is ongoing. It is answered in the readme: https://github.com/dotnet/wpf/blob/master/README.md#status
And on the roadmap: https://github.com/dotnet/wpf/blob/master/roadmap.md

**Comment by stevenbrix** [comment]
It's coming! As part of moving WPF to .NET Core 3, we've had to adopt an entirely new build system (see http://github.com/dotnet/arcade).  This move hasn't been trivial, and it is a prerequisite before we can move the majority of our code into this repo. We started with System.Xaml since it had the least amount of dependencies between other WPF assemblies and so getting it to build on Arcade was trivial.

We apologize that this is taking so much time, but I assure you we are working on it and fully intend to open source everything shortly!

**Comment by fabiant3** [comment]
Echoing @stevenbrix comment, expect to see another assembly's source code being published within the next couple weeks. Arcade eat into our "source porting" scheduled time, but we've been equally busy making progress porting our gigantic test infrastructure. Moving forward it is expected that we'll be open sourcing more code at a faster pace for sure.

**Comment by stevenbrix** [comment]
I'm going to go ahead and close this issue. Thank you for the continued interest and patience!
