### ISSUE TITLE
A11y_.NETWPF_DataBindingDemo_ListOfProducts_AI4D: (DataBindingDemo/list item ' Color: Highlight, Description: My DVD Collection, Current price: $8') An element's IsOffScreen property must be false when its clickable point is on screen.

### ISSUE THREAD

**Issue by Blessymanna** [dotnet/wpf#5046]
The following accessibility issue needs investigation.
GitHubTags:#A11yMAS;#A11ySev2;#A11yTCS;#A11yWCAG;#DesktopApp;#WCAG4.2.1;#DesktopApp;#Win10;#BM-.NetCore(WPF)-Win32-July2021;#.NET Core;#Benchmark;#A11yAuto;
**App:** DataBindingDemo

**Environment Details**:
Application Name: .NET Core WPF
Microsoft .NET Core SDK Version 6.0.100-rc.1.21380.2
Windows Version: Windows10

**Repro Steps**:

1. Launch VS 2019 Int Preview
2. Navigate to Sample Applications and right click on the DatabindingDemo and tab navigate to build.
3. Then tab navigate to by right clicking on DatabindingDemo then Click on Debug-->Start New Instance. 
4. List of products screen should open.
5. Verify all the elements of 'DatabindingDemo_List of Products' screen are accessible and MAS Compliant

**Element path:** list item ' Color: Highlight, Description: My DVD Collection, Current price: $8'

**Issue Details:** An element's IsOffScreen property must be false when its clickable point is on screen. [Section 508 502.3.1](https://www.access-board.gov/ict/#502-interoperability-assistive-technology)

**How To Fix:** If the element's ClickablePoint property is correct, set the element's IsOffScreen property to false.
If the element's ClickablePoint property is incorrect, please ensure it returns the correct value.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

**Comment by dbjorge** [comment]
Hi,

I'm an Accessibility Insights developer. I just wanted to write in and mention that we receive reports from our users because of this framework issue with some regularity ([example 1](https://github.com/microsoft/axe-windows/issues/539), [example 2](https://github.com/microsoft/accessibility-insights-windows/issues/1176)). We believe that this issue is a true positive, ie, a legitimate issue with WPF which Accessibility Insights is catching. Specifically, for these list items which are obscured from view, WPF is correct to report the out-of-view list items as "IsOffScreen = true", but incorrect to report them as having clickable points. The discussion in [axe-windows#539](https://github.com/microsoft/axe-windows/issues/539) has some more detailed analysis.

**Comment by anjalisheel-wpf** [comment]
@dbjorge This issue has been addressed already. I have tested it, providing the link for the PR : https://github.com/dotnet/wpf/issues/4631
