### ISSUE TITLE
Exception with CollectionView object when participate in synchronized access

### ISSUE THREAD

**Issue by ddddtse** [dotnet/wpf#5060]
* .NET Framework Version: 4.8
* Windows version: Windows 10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No

 
 
 **Problem description:**
We were using **BindingOperations.EnableCollectionSynchronization** method with a simple lock to make an observable collection accessible on multi-thread. Program crashes sometimes and we cannot figure out a way to precisely reproduce this issue. The actual class and stack trace is shown below.  It seems like the program crashes within the framework because the exception didn't happen with [ObservableCollection.RemoveItem](https://referencesource.microsoft.com/#System/compmod/system/collections/objectmodel/observablecollection.cs,199). 
```C#
protected override void RemoveItem(int index)
{
    CheckReentrancy();
    T removedItem  = this[index];

    base.RemoveItem(index);  // If there's problem with removing item on multi-thread, the program should crash here.

    OnPropertyChanged(CountString);
    OnPropertyChanged(IndexerName);
    OnCollectionChanged(NotifyCollectionChangedAction.Remove, removedItem, index); // Instead, the program crashes after execution of this statement.
}
```

Can you please tell me if we were implementing the multi-thread accessible observable collection in a wrong way or if there's a bug with the framework? More importantly, can you please tell me if there's a workaround or substitute for this kind of class?

```C#
public class AsyncObservableCollection<T> : ObservableCollection<T>
{
    private readonly object _lock = new object();

    public AsyncObservableCollection()
    {
        BindingOperations.EnableCollectionSynchronization(this, _lock);
    }

    public AsyncObservableCollection(IEnumerable<T> list)
        : base(list)
    {
    }

    public new void Add(T item)
    {
        lock (_lock) base.Add(item);
    }

    public new bool Remove(T item)
    {
        lock (_lock) return base.Remove(item);
    }

    public new void Insert(int index, T item)
    {
        lock (_lock) base.Insert(index, item);
    }

    public new void Clear()
    {
        lock (_lock) base.Clear();
    }

    public new T this[int index]
    {
        get
        {
            lock (_lock)
                return base[index];
        }
        set
        {
            lock (_lock)
                base[index] = value;
        }
    }

    public List<T> ToList()
    {
        lock (_lock) return new List<T>(this);
    }
}
```
 
 **Actual behavior:** 
 应用程序: Pipeline.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.ArgumentOutOfRangeException
   At System.Collections.ArrayList.RemoveAt(Int32)
   At System.Windows.Data.ListCollectionView.AdjustShadowCopy(System.Collections.Specialized.NotifyCollectionChangedEventArgs)
   At System.Windows.Data.ListCollectionView.ProcessCollectionChanged(System.Collections.Specialized.NotifyCollectionChangedEventArgs)
   At System.Windows.Data.CollectionView.ProcessChangeLog(System.Collections.ArrayList, Boolean)
   At System.Windows.Data.CollectionView.ProcessInvoke(System.Object)
   At MS.Internal.Data.DataBindOperation.Invoke()
   At MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   At System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   At System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   At System.Windows.Threading.DispatcherOperation.InvokeImpl()
   At System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   At MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   At System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   At System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   At System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   At MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   At System.Windows.Threading.DispatcherOperation.Invoke()
   At System.Windows.Threading.Dispatcher.ProcessQueue()
   At System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   At MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   At MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   At System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   At System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   At System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   At MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   At MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   At System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   At System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   At System.Windows.Application.RunDispatcher(System.Object)
   At System.Windows.Application.RunInternal(System.Windows.Window)
   At System.Windows.Application.Run(System.Windows.Window)
   At PipelineDebug.App.Main()

 **Expected behavior:**
 
 **Minimal repro:**

**Comment by SamBent** [comment]
@ddddtse - This is probably your bug, for failing to meet one of the responsibilities listed in the [doc](https://docs.microsoft.com/en-us/dotnet/api/system.windows.data.bindingoperations.enablecollectionsynchronization?view=net-5.0#remarks):

```Synchronize all access from the application to the collection using that mechanism.```

It's not enough to lock the low-level operations, as that doesn't synchronize more complex operations that should be run atomically.  Only the app knows what those operations are.  This is why .NET stopped including SyncRoot in the collection interfaces (compare `IList` with `IList<T>`).  It only works in toy apps;  real apps need to do something stronger.

Insufficient synchronization leads to subtle bugs that can affect your app's behavior independent of WPF.  You're seeing a crash in WPF only because WPF is the most active cross-thread participant;  the root problem would affect other participants (i.e. app logic running on different threads) even if WPF weren't present, if they happen to hit a similar pattern of access and timing.

I can't be sure of all this without seeing a repro, of course.  But I've looked at dozens of similar complaints, and every one of them has been the app's fault for not synchronizing correctly.

**Comment by ddddtse** [comment]
@SamBent - Can you please kindly give me an example of the low-level operations you were referring to?

In the repo I only used the access operations listed in the `AsyncObservableCollection` and bound the collection in .xaml files. No other modification is made to the collection in my code without the methods listed. 

So given this perspective, I did `"Synchronize all access from the application to the collection using that mechanism."` and yet the app still crashes without any pattern of access and timing so it is really hard for me to track. 

Thanks in advance.

**Comment by SamBent** [comment]
@ddddtse - By "low-level operations", I meant the ones you quoted.  You used 'new', which only protects direct calls from your code, and even then only calls to objects with compile-time type AsyncObservableCollection.  That leaves plenty of opportunities for unprotected calls, including
* calls through a base type or interface, e.g. `(myCollection as ICollection<MyClass>).Add(item)`
* indirect calls:  `myCollection.Foo()`, where Foo is a method of ObservableCollection that calls Add
* indirect usage through an enumerator: `foreach (item in myCollection) {...}`
* indirect usage through LINQ queries or extension methods
* (many others)

It's difficult to spot the problem, especially in the indirect cases where the problem is in usage of code you don't own.  Nevertheless, it's your job to find it;  we (readers of this page) know nothing about your code or dataflow, so we have no way to even begin looking for the problem.

One suggestion:  try to get a time-travel trace of the crash.  If you can, find all the calls to the collection view's CollectionChanged handler:
```
class System.Windows.Data.CollectionView
{
        protected void OnCollectionChanged(object sender, NotifyCollectionChangedEventArgs args)
}
```
Look at the callstacks to find ones that don't lock your `_lock` object.
(This often finds the problem, but I can't guarantee it.)

You can do this while live debugging too, but the advantage of TTD is that you aren't depending on timing and race conditions to trip over the problem.

**Comment by ddddtse** [comment]
@SamBent - It was cause by a bug in my code indeed. 
Thank you very much. The possibilities you listed for unprotected calls helped a lot.

If you are interested in what I did wrong, please keep reading, otherwise you can close the page now. ;)

What I did wrong: 
I accidentally declared an instance `myCollection` as `ObservableCollection` and then instantiated `myCollection` with `AsyncObservableCollection`. 

How it crashed: 
With the new keyword used for `AsyncObservableCollection.Clear()` and `myCollection` declared as an `ObservableCollection` , `myCollection.Clear()` was actually calling `ObservableCollection.Clear()` instead. Since `ObservableCollection.Clear()` doesn't have a lock mechanism, it would have a problem being modified by multi-thread.

Fixes:
1. Fix the declaration of `myCollection`.
2. Rewrite `AsyncObservableCollection<T>`, make it implement `IList<T>`, `IList`, `IReadOnlyList<T>`, `INotifyCollectionChanged`, `INotifyPropertyChanged` and add lock mechanism for all interface implementations to avoid any possible indirect usages of the instance.

Thanks again for your kind reply.
