### ISSUE TITLE
Support ImplicitUsings for WPF

### ISSUE THREAD

**Issue by OliaG** [dotnet/wpf#5790]

**Comment by RussKie** [comment]
https://docs.microsoft.com/dotnet/core/whats-new/dotnet-6#c-10-and-templates is a good starting point.

You can also see how dotnet/winforms updated the .NET 6+ templates to accommodate top level statements, implicit usings, and other C# 10 language constructs here https://github.com/dotnet/winforms/tree/main/pkg/Microsoft.Dotnet.WinForms.ProjectTemplates. You may find https://github.com/dotnet/winforms/issues/5171 somewhat useful.

**Comment by miloush** [comment]
If usings are moved to implicit I would suggest a review of the list of usings and a bit more conservative approach, especially since the tooling can now offer types from non-imported namespaces. For example, I use `Path` as `System.IO.Path` much more often than `System.Windows.Media.Path` which is currently the default import.
