### ISSUE TITLE
PublishTrimmed is causing error when building WPF in VS2022 Preview 4

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5909]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PublishTrimmed-is-causing-error-when-bui/1529981)._

---
[regression] [worked-in:VS2022 Preview 4]
I installed the latest preview and while I had <PublishTrimmed>true</PublishTimmed> in all my projects before it now shows:

Error	NETSDK1168	WPF is not supported or recommended with trimming enabled. Please go to https://aka.ms/dotnet-illink/wpf for more details.	
C:\Program Files\dotnet\sdk\6.0.100-rc.1.21458.32\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets	178	

I understand the recommandation but it 1. worked before and 2. has nothing to do with publishing. I thought the <Publish...> properties are only active when publishing and not while building or running?

Any advice?

Thanks.

---
#### Feedback Bot on 9/16/2021, 01:58 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/3/2022, 11:03 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ThomasGoulet73** [comment]
There is an undocumented MSBuild that can be used to ignore this error: `_SuppressWpfTrimError`. You simply need to add this to your project to ignore the error: `<_SuppressWpfTrimError>true</_SuppressWpfTrimError>`.

As for the error happening on build even though `PublishTrimmed` is only happening on publish, I believe that is by design. There are other errors next to this one that can happen on build for `<Publish...>` properties: https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets#L150-L179.

**Comment by gurpreet-wpf** [comment]
@ThomasGoulet73  Thank you for  providing the solution to suppress the warning. This shall help get build passed. Although, complete trimming compatibility for WPF is in the feature enhancement request.  #3811
