### ISSUE TITLE
Wpf app display a white dot when touch moving on touch device like tablet

### ISSUE THREAD

**Issue by luojunyuan** [dotnet/wpf#5914]
Only app build with wpf has this issue, I've never seen such white dot in other gui programs on my computer(not test winform yet). Instead of win10 native touch moving animation. There is always a white point follows finger moving.
![image](https://user-images.githubusercontent.com/28323948/148447945-cc8eeed9-22e9-4b3c-bec9-89aff87db99d.png)

Relative thread: https://stackoverflow.com/questions/48074613/how-to-remove-white-touch-dot-on-windows-10

Is there any other way to turn back the win10 touch moving animation? (a transparent line follow with finger fluently, I can't catch that with screenshot)

I tried `EnablePointerSupport` but it will effect some Window default behavior when using touch make it even worse.
Override `Window.OnPreviewTouchMove` did the job but still not stable works. When you drag the title bar with finger, That white dot will definitely appear.

**Comment by miloush** [comment]
As already suggested by the SO thread, this is a Windows feature coming from Windows Ink, introduced with Windows 10 Anniversary Update. You can see it all over in the videos in this blog: https://blogs.windows.com/windows-insider/2016/04/22/a-closer-look-at-windows-ink/

It depends on the hardware/driver whether it produces pointer or touch events, and as also mentioned, it depends on the stack which you can control using `EnablePointerSupport`.

Since this is Windows built-in cursor, you would need to do whatever you need to hide a standard cursor, such as setting `Cursor` to `None`. The same applies to the title bar and it is more difficult to hide a cursor on title bar (one option is to use WindowChrome to extend the client area to it). That said, as a user, I would have similar feelings as when you tried to hide cursor from me.

Have you tried hiding the cursor/visual effects in pen settings?
![ss](https://blogs.windows.com/wp-content/uploads/prod/sites/3/2016/11/Picture34.png)

Either way I don't think there is anything to fix on the WPF side.
