### ISSUE TITLE
Tests solution doesn't build in VisualStudio

### ISSUE THREAD

**Issue by rookie0jnr** [dotnet/wpf#599]
****.NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)****
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011322
 Commit:    3d3dd1648a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview5-011322\

Host (useful for support):
  Version: 3.0.0-preview5-27616-01
  Commit:  e32693473d

.NET Core SDKs installed:
  2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
  2.2.300-preview-010046 [C:\Program Files\dotnet\sdk]
  3.0.100-preview5-011322 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19215-07 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27616-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview5-27616-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

****Windows version: (`winver`)****
Version 1803 (OS Build 17134.706)

****Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes/No****
I don't think that this happens in WPF for .NET Framework 4.8.

 
 
****Problem description:****
I cloned this repository, performed build.cmd and open the Tests.sln in VisualStudio 2019 preview. And the solution does not build. It seems that the problem is in the BamlAvoidXmlTest project and in the references that it has.It seems that NuGet cannot find/resolve these dependencies. Please check the attached screen-shot. 
Please note also, that the tests can be executed from the command line. But my main goal is to examine/execute/debug these tests from VisualStudio.
Am I missing something? Are there some additional steps/conditions needed in order to build/execute this tests within TestStudio?  
 
![NuGet errors](https://user-images.githubusercontent.com/48907761/56266132-27f27a80-60f4-11e9-94ba-5fbc71e2ffe1.JPG)

**Comment by ryalanms** [comment]
+@ojhad, @miguep.

**Comment by vatsan-madhavan** [comment]
To solve this right, I think we need to adopt (for tests) `RuntimeTargetFramework `+ `TargetingPackVersion `+ an update to `tools.dotnet/sdk.version` in global.json, likely all predicated on https://github.com/dotnet/arcade/pull/2343 becoming available. 

Then likely we'll have to merge the test-projects into the main solution (i.e., not maintain two separate solutions) and using `Microsoft.NET.SDK `exclusively for builds (instead of using `Micoroft.NET.Sdk.WindowsDesktop`, which is an odd self-referential way of building tests). 

I have a prototype in the works that I created as part of https://github.com/dotnet/wpf/pull/604 (and the original `RuntimeTargetFramework `PR) that I was working on last week. 

A short term workaround might look like this, although I wouldn't recommend that we fix it this way (esp. since https://github.com/dotnet/arcade/pull/2343  will likely become available next week-ish). 

```XML
<KnowFrameworkReference Remove="Microsoft.ApsNetCore.App" Condition='''$(WpfTest)'=='true'" />
```

**Comment by rladuca** [comment]
This should be fixed now, resolving.
