### ISSUE TITLE
Binding errors when running in Visual Studio but not when directly executing the EXE

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#6137]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Binding-errors-when-running-in-Visual-St/1463517)._

---
[severity:It bothers me. A fix would be nice]
(This is a repost of [this issue](https://developercommunity.visualstudio.com/t/Binding-errors-when-running-in-Visual-St/1294226) that I think was improperly closed and, as far as I can tell, never consider for reopening as I requested.)

I am trying to fix some binding errors as I describe in [this issue](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2196).  In the process of investigating that issue, I discovered that those binding errors happen when running the application through Visual Studio but not when directly executing the EXE.

# Steps to reproduce
1. Obtain my reproduction either form the attached ZIP, the [same ZIP from my Dropbox](https://www.dropbox.com/sh/pwy6nqdru2km0qr/AABfZfmyFQNZMfwEFSKkG-tda?dl=0), or [this repository](https://github.com/TysonMN/MaterialDesignInXaml_DataGrid_reproduction).
2. Build the code
3. Run the application, either from within Visual Studio or by opening the EXE (see GIFs below)
4. Click the button "Set level to Warning" (only necessary when directly executing the EXE)
5. Click the header of the DataGrid

# Expected behavior
I expect either choice in step 3 to lead to the same behavior.  (That binding errors happen at all when executing from Visual Studio is the _unexpected_ behavior in the linked issue.)

# Actual behavior
The choice in step 3 leads to different behavior.  When executing from Visual Studio, there nine binding errors.  When directly executing the EXE, there are no binding errors.

# When executing from Visual Studio
[GIF] (https://www.dropbox.com/s/qkv9jnx7s4u17nx/Execute_from_Visual_Studio.gif)

# When directly executing the EXE
[GIF] (https://www.dropbox.com/s/yivdtishjvphgh2/Execute_from_bin_folder.gif)

---
#### Feedback Bot on 6/30/2021, 02:36 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/9/2021, 02:05 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

#### Mila Zhou[MSFT] on 1/21/2022, 00:40 AM: 

<p>Thank you for taking the time to log this issue! Did you still reproduce this issue in the latest stable version of Visual Studio installed from <a target='_blank' href="https://visualstudio.microsoft.com/downloads">https://visualstudio.microsoft.com/downloads</a> ?<br>
If so, could you please provide a sample solution that has this problem so that we can conduct further research?</p>
<p>We look forward to hearing from you!</p>

#### Tyson Williams on 1/30/2022, 07:06 PM: 

<p>Hello Mila,</p>
<p>Yes, I just reproduced the problem using version 17.0.5 of Visual Studio.</p>
<p>I have already provided a sample solution and reproduction steps in my original post.</p>

#### Feedback Bot on 2/8/2022, 07:02 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by miloush** [comment]
This is by design, tracing has to be enabled, see https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.presentationtracesources?view=windowsdesktop-6.0.

Either the registry value described in remarks must be set, or `PresentationTraceSources.Refresh()` needs to be called - in the repro project after the source is added but before the desired level is set.

**Comment by anjalisheel-wpf** [comment]
Yes, this is as per the design. You can refer the link shared by Miloush.

Errors are simply due to deferred loading. It's very common to see transient data binding errors. You could try adding this code to enable verbose binding information for that particular binding:

'PresentationTraceSources.SetTraceLevel(b, PresentationTraceLevel.High);'

Add that before you call 'SetBinding'. Try single stepping through the code. If you see the error message you describe at the point at which you call 'SetBinding', and then if you hit F5, you see a load more binding messages appearing, particularly if it includes a 'DataChanged' event from the 'XmlDataProvider', then this is almost certainly the reason.

If you really don't want to see these transient errors, you would need to create these bindings after the 'XmlDataProvider' has finished loading its data.
