### ISSUE TITLE
MediaPlayer cant play the uri startswith `pack://...`

### ISSUE THREAD

**Issue by emako** [dotnet/wpf#6185]
* .NET Core Version: 6.0.2
* Windows version: win11
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Dont know
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? NO
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/main/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:**
 
MediaPlayer cant play the uri startswith `pack://...`.
such as 
```cs
// play failed
string uriString1 = $"pack://application:,,,/Lyre.Player.Plugin;component/Resources/FloralZither.mp3";
MediaPlayer player1 = new();
player1.Open(new Uri(uriString1));
player1.Play();

// play ok
string uriString2 = @$"D:\GitHub\Snap.Genshin\Plugins\SG.Plugin.Lyre.Player\src\Resources\FloralZither.mp3";
MediaPlayer player2 = new();
player2.Open(new Uri(uriString2));
player2.Play();
```

 **Actual behavior:** 
`UriSchemePack` type uri cant be played using MediaPlayer.

 **Expected behavior:**
 
 **Minimal repro:**

**Comment by lindexi** [comment]
I wrote a demo to reproduce this problem: https://github.com/lindexi/lindexi_gd/tree/af15cde4b0628c2744a8b8eac14a791e2d4f7b54/KufayunurharnaLuragaruker

**Comment by ThomasGoulet73** [comment]
MediaPlayer is a wrapper around the [Windows Media Player](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/api/_wmp/) which, to my knowledge, only supports path and URLs. You could extract the file from the assembly, save it to a file, play the file and then delete the file. This is not ideal but for small files (Which I suppose is your case since it doesn't really make sense to embed large file inside the assembly), it should be fast enough.

**Comment by lindexi** [comment]
@ThomasGoulet73 How about throw an exception when input the `pack://` uri?

**Comment by emako** [comment]
> MediaPlayer is a wrapper around the [Windows Media Player](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/api/_wmp/) which, to my knowledge, only supports path and URLs. You could extract the file from the assembly, save it to a file, play the file and then delete the file. This is not ideal but for small files (Which I suppose is your case since it doesn't really make sense to embed large file inside the assembly), it should be fast enough.

Does MediaPlayer intend to append the API that passes the `Stream` parameter for opening file?

**Comment by lindexi** [comment]
![图片](https://user-images.githubusercontent.com/16054566/156101937-4379f6c7-526c-421d-8562-da3185426532.png)

Good catch. It will raise the MediaFailed event.

**Comment by ThomasGoulet73** [comment]
You were faster than me 😄. Here's the code that throws when using pack for reference:
https://github.com/dotnet/wpf/blob/4af440108d50958a2ac3e3f67a454aa0cd142e5c/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaPlayerState.cs#L844-L855

`Does MediaPlayer intend to append the API that passes the Stream parameter for opening file?`
This repo is probably not right place to ask this question since it is probably maintained by the Windows team. I would recommend using third-party solutions which might support using a `Stream` (VLC based player might support it).

**Comment by emako** [comment]
Try VLC or extract the file from the assembly to fix problem.
