### ISSUE TITLE
Selection in WPF ComboBox cannot be changed if the ItemsSource is populated with objects defined as "record" instead of "class" and SelectedItem is bound to a property of the view model.

### ISSUE THREAD

**Issue by martinivanoff** [dotnet/wpf#6379]
* .NET Core Version: 6.0.3
* Windows version: 19044.15876
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Not tested.
 
 **Problem description:**

Selection of the __WPF ComboBox__ control cannot be changed if the ItemsSource is populated with objects defined as `record` instead of `class` and the __SelectedItem is bound__ to a property in the view model.

The issue appears in the WPF framework under .NET 6. 

The attached project shows the described behavior. In the project, just try to select an item by opening the drop down and clicking onto any item. 
[WpfApp59.zip](https://github.com/dotnet/wpf/files/8441575/WpfApp59.zip)

What I mean by `record` is the following:
```
public record DataInfo
{
}
```
 
 **Actual behavior:** 

When you run the project and open the ComboBox drop down, click on any item to select it. At this point nothing happens. The selection cannot be changed. If you subscribe to SelectionChanged, you will see that actually the clicked item is selected and then the selection is returned back to the previous one.
 
 **Expected behavior:**
 
The selection should be changed properly when you click on an item in the drop down.

 **Minimal repro:**

 ```
<ComboBox ItemsSource="{Binding Items}" 
                  SelectedItem="{Binding SelectedItem, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
                  DisplayMemberPath="Name"
                  VerticalAlignment="Center"
                  Width="300"/>       
```
```
public class MainViewModel : INotifyPropertyChanged
    {
        private DataInfo selectedItem;
        public DataInfo SelectedItem
        {
            get => selectedItem;
            set { selectedItem = value; OnPropertyChanged("SelectedItem"); }
        }
        public ObservableCollection<DataInfo> Items { get; set; }

        public MainViewModel()
        {
            this.Items = new ObservableCollection<DataInfo>();
            for (int i = 0; i < 10; i++)
            {
                Items.Add(new DataInfo() { Name = "Item " + i });
            }
            SelectedItem = Items[3];
            
        }

        protected void OnPropertyChanged([CallerMemberName] String propertyName = "")
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        public event PropertyChangedEventHandler? PropertyChanged;
    }

    public record DataInfo : INotifyPropertyChanged
    {
        private string name;

        public string Name
        {
            get { return name; }
            set { name = value; OnPropertyChanged("Name"); }
        }

        protected void OnPropertyChanged([CallerMemberName] String propertyName = "")
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        public event PropertyChangedEventHandler? PropertyChanged;
    }
```

**Comment by miloush** [comment]
Why would you use a property changed event, or any event handler to begin with, on a type with value equality?

You can reproduce the issue without records:

```C#
public class DataInfo : INotifyPropertyChanged
{
    public string Name { get; set; }
    public event PropertyChangedEventHandler PropertyChanged;

    public override int GetHashCode() => Name.GetHashCode() ^ PropertyChanged?.GetHashCode() ?? 0;
}
```

The problem is your data type does not have a reliable hash code. When items are added to items collection, they are stored in a dictionary. Then the WPF subscribes to the `PropertyChanged` event, making the handler field non-null and effectively changing the instance's hash code. When you later want to set the selected item, it appears like the new item is not in the items collection at all (since it has a different hash code) and the selection gets deferred.

Now, internally, WPF has provisions for working with items with unstable hash code. But these offenders are kept on a special list in which the assembles have to register any such types. Hypothetically this registration could be made publicly available, but I don't see any convincing reason to do so.

Do not use types that change their identity when WPF touches them.
