### ISSUE TITLE
The PathGeometry filling fails when its transformation is modified

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#643]
<p>Hello Microsoft Support,<br>I've created a simple filled rectangle using LineSegment and PathGeometry objects, rendering it using a DrawingVisual object into a FrameworkElement container. At creation everything works well, but as soon as the transformation matrix is changed, the rectangle loses its filling.<br>I've attached a complete solution that show the problem: naturally it is very simple while we use more <a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/68780-pathgeometryfillfailed.zip">pathgeometryfillfailed.zip</a>complicated figures using also curves applying to it zoom and pan features.<br>Let me point out, that this issue is very serious for us because it doesn't allows to go on in our work.<br>Thank you in advance.<br>Best regards,</p><p>Simone</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/535529/the-pathgeometry-filling-fails-when-its-transforma-2.html
VSTS ticketId: 848623_
_These are the original issue comments:_

Visual Studio Feedback System on 4/16/2019, 08:27 PM (16 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by Simon-IT** [comment]
This issue impact our CAD program as [642](https://github.com/dotnet/wpf/issues/642). I've spent much time to investigate it because the logic and the rendering code of WPF are very complicated. The problem is that the corresponding UCE resources (I think it are in the MIL component) are not updated when Transform property changed is triggered to the geometry object. In our CAD program much shapes are filled by a color and so, when we transform the geometry as in pan feature, the filler is lost.
A note. I asked myself, Why doesn't this behavior happen with the same geometry into a Path object ? Because Path object is a UIElement derived type and so partecipates into the layout system. In some point of the arrange o measure procedure, the UCE resources are released and recreated. Also this is a genuine framework bug. @grubioe can we get that reclassified and not put on 'future'?
Thank you

**Comment by Simon-IT** [comment]
For contributing more and for giving a suggestion, in **PresentationCore->System->Windows->Media->Generated->Geometry.cs** file, in **Geometry.TransformPropertyChanged** static method if you add a call to **target.PropertyChanged(TransformProperty);** not only at the end of the method as it is , but elesewhere before to exit, all works well. Of course, I don't know all the implications of this solution given the complexity of the resource management.

**Comment by Simon-IT** [comment]
Hi,
is there a possibility to have resolved the issue for 5.0 milestones ?
Thanks

**Comment by Simon-IT** [comment]
Hi,
please any news about this issue ?
Thanks

**Comment by Simon-IT** [comment]
Hi,
please any news about this issue ?
Thanks
