### ISSUE TITLE
GridSplitter does not work when IsItemsHost is true

### ISSUE THREAD

**Issue by IAmTheCShark** [dotnet/wpf#6490]
* .NET Core Version: 5.0
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

`GridSplitter` does not work, when it is added programmatically to `ItemsControl.Items` that uses a `Grid` with `IsItemsHost="true"`
 
Reason:
[`GridSplitter.InitializeData` ](https://source.dot.net/#PresentationFramework/System/Windows/Controls/GridSplitter.cs,493)checks if `Parent` is a `Grid`. In this case the `LogicalParent` is the `ItemsControl`.
Shouldn't it check the `VisualParent`?
[repro.zip](https://github.com/dotnet/wpf/files/8571712/repro.zip)

**Comment by miloush** [comment]
`VisualParent` sounds reasonable to me. If there is a worry about backward compatibility, `VisualParent` can be checked only if `Parent` does not turn out to be `Grid`.

**Comment by IAmTheCShark** [comment]
@miloush I thought the same.
I'd create a pull request depending on how backwardscompatibility should be treated. Let's see.

**Comment by miloush** [comment]
Technically you can use `ContentControl` to use a template for `Grid`. There are also some edge cases, such as `ContentControl` not setting itself as a logical parent if it is in a control template and the content already has a parent, which you might be able to leverage, but at the end of the day it's up to the parent to construct the logical tree as it pleases, so classes deriving from `Grid` can easily create a scenario which would be affected (example in PR).

That said, it seems to me that the `ItemsControl` (as well as `ContentControl`) do extra work to not set the panel as a logical parent of items. I am starting to worry that doing as proposed in this issue actively circumvents this design decision of separation.

Can you say a bit about the use case?

**Comment by IAmTheCShark** [comment]
I updated the PR accordingly to check the LogicalParent first.

@miloush there is no "extra" work involved when you check out my reproduction. Myabe I do not understand you correctly here, but I did nothing explicitely to mess with the logical parents structure. But since you provided an example I realized there is alot more possibilities to resolve the original use case we have.

**Comment by IAmTheCShark** [comment]
Closing this issue because im not 100% sure anymore if this was a good idea.

**Comment by miloush** [comment]
@IAmTheCShark yes sorry I meant the WPF is doing extra work. The purpose of `Panel.IsItemsHost` is to prevent the panel from having logical children. Similar with `ContentControl.ContentIsNotLogical` which is used with items. Your PR would make some of the items sometimes see the panel and that worries me. Maybe an opt-in (or associating `GridSplitter` with a custom `Grid`) would do. Maybe my counterexample is artificial and I am overly cautious, while everyone would expect the behavior you are expecting and `GridSplitter` in fact should have checked visual parent. You can also create your own `GridSplitter` that behaves as suggested, although sadly this aspect is not easily overridable.

I have used `Grid` as items panel many times, however, never with a `GridSplitter`. That's why I was enquiring about the scenario.

**Comment by miloush** [comment]
The inconsistency is most visible when the items control overrides `IsItemsIsOwnContainer`. For example, while `GridSplitter` in pure `ItemsControl` would work, it wouldn't work in `ListBox` as its visual parent would be `ContentPresenter`. I am getting more and more convinced myself this is not a good idea.
