### ISSUE TITLE
DateTime.TryParseExact() method fails 

### ISSUE THREAD

**Issue by SwathiDhatchanamoorthi** [dotnet/wpf#6716]
I have tried to format object  value into DateTime using TryParseExact() method but this method will always returns false. I have used the below codes,

 private void Button_Click(object sender, RoutedEventArgs e)
        {
           object cellValue;
            DateTime columnValue;
            cellValue = new DateTime(1999, 1, 13, 3, 57, 32, 10); 
            if(DateTime.TryParseExact(cellValue.ToString(), "hh:mm:ss.fff", CultureInfo.InvariantCulture, DateTimeStyles.None, out columnValue))
            {
                MessageBox.Show(columnValue.ToString());
            }
            else
            {
                MessageBox.Show("Wrong value");
            }
        }

I need to convert the DateTime value with milliseconds. 
Can you kindly provide any solution for this ?

**Comment by batzen** [comment]
Your issue is not related to WPF.

TryParseExact tries to parse the string you give it exactly as you specified, but your input string also contains the year, month and date.

Given your last sentence it's not clear to me if you want to format your DateTime or parse it. If you want to format it, just pass the string you pass to TryParseExact to the ToString call on your DateTime.
If you want to parse it just use TryParse and not TryParseExact.

**Comment by dipeshmsft** [comment]
Since, this is not related to WPF, closing this issue. Thanks @batzen for the quick response.
