### ISSUE TITLE
XAML {x:Static FooClass.Border} will be compiled unexpectedly to {x:Static SystemParameters.Border}

### ISSUE THREAD

**Issue by walterlv** [dotnet/wpf#679]
* .NET Core Version: 3.0 Preview5
* Windows version: 10.0.18895.1000
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 
 
 **Problem description:**

When assigning a WPF dependency property using `x:Static` markup extension and pass a CLR property named `Border` into it, the XAML compiler will compile this static property to `SystemParameters.Border` which is not expected.

 **Actual behavior:**

This first one will be compiled to the second.

```xml
<!-- The original code -->
<Button Content="{x:Static local:FooClass.Border}" />
```

```xml
<!-- The compiled code -->
<Button Content="{x:Static SystemParameters.Border}" />
```

 **Expected behavior:**

XAML compiler should not change the original property assigning of `x:Static` markup extension.
 
 **Minimal repro:**
 
1. Create a WPF (.NET Core / .NET Framework) project;
1. Write a class with a static property named `Border`;
1. Write a `x:Static` usage in a XAML file.

You can view the minimal reproduction on my GitHub project here:

- [walterlv/XamlBugs.StaticProperties](https://github.com/walterlv/XamlBugs.StaticProperties)

The key codes are here:

```csharp
// This namespace can be changed to any other and the bug still reproduces.
namespace XamlBugs.StaticProperties
{
    /// <summary>
    /// The class that provide a `Border` property.
    /// You can change this class name to any other and the bug still reproduces.
    /// </summary>
    public static class FooClass
    {
        /// <summary>
        /// The correct value for this property is `string.Empty`, but you'll see `1` in actual.
        /// </summary>
        public static string Border => "";
    }
}
```

```xml
<Window x:Class="XamlBugs.StaticProperties.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:XamlBugs.StaticProperties"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>

        <!-- When you run this application, and you'll see an incorrect content value of this `Button`.
             If you try to decompile this assembly and view the mainwindow.baml file,
             you'll find that the static value has been changed to `SystemParameters.Border` -->
        <!-- The XAML namespace prefix can be changed to any other and the bug still reproduces. -->
        <Button Content="{x:Static local:FooClass.Border}" />

        <!-- Don't uncomment this line, because it will cause a runtime error.
             The `FooClass.Border` property is a string,
             but it will be compiled to `SystemParameters.Border` which is not a string. -->
        <!--<TextBlock Text="{x:Static local:FooClass.Border}" />-->
        
    </Grid>
</Window>
```

**Comment by walterlv** [comment]
If you run this application, you'll see the value is from `SystemParameters` but not from `FooClass`:

![image](https://user-images.githubusercontent.com/9959623/57596008-edf18880-757a-11e9-9c31-9e3473487cfa.png)

**Comment by NaBian** [comment]
I had the same problem: [bug](https://github.com/HandyOrg/HandyControl/blob/bc89baf2fa1c48e239441a4001bc3e6e08039a57/src/Shared/HandyControlDemo_Shared/UserControl/Main/LeftMainContent.xaml.cs#L25)

**Comment by noctwolf** [comment]
I analyzed it, it should be a bug in the ProvideValue of System.Windows.Markup.StaticExtension, or [TypeConverter(typeof(StaticExtensionConverter))]. Produced during serialization and deserialization, but I won't debug this

**Comment by weltkante** [comment]
The Extension and the TypeConverter is correct (even though the TypeConverter forgets to serialize the MemberType property that is not the cause of the bug, since MemberType is null in this case). Instead the bug is in the markup compiler which has special handling for static extensions.

The special handling for the static extension is in the [BamlMapTable](https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlMapTable.cs#L1506), when it sees a property it will ask [SystemResourceKey.GetBamlIdBasedOnSystemResourceKeyId](https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResourceKey.cs#L362) to check if this is a static SystemResourceKey access (returns zero if not). Unfortunately this method ignores the targetType passed as argument and only [parses the memberName](https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResourceKey.cs#L392).

So if you have any property named like a SystemResourceKeyID (the enum can be found above in the same file) it will be treated as such, regardless of the type its defined on.

Possible Workarounds
* Make `FooClass.Border` a field not a property. The bug is only triggered with properties.
* specify the MemberType explicitely as `{x:Static Border, MemberType={x:Type local:FooClass}}` - this will compile correctly, but the designer doesn't like it

**Comment by walterlv** [comment]
I found that the possible incorrect code is here:

- [SystemResourceKey.GetBamlIdBasedOnSystemResourceKeyId](https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResourceKey.cs#L392)

```csharp
try
{
    srkId = (SystemResourceKeyID)Enum.Parse(typeof(SystemResourceKeyID), srkField);
}
catch (ArgumentException)
{
    found = false;
}
```

This method is called by [BamlMapTable.GetStaticMemberId](https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlMapTable.cs#L1515).

The problem is that if the property name matches `SystemResourceKey` enum, the owner class will be ignored and the value will be from `SystemParameters` but not the correct owner class.

**Comment by weltkante** [comment]
Apprently we found the bug cause at the same time ;-) Yes the problem is that above method doesn't check the `targetType` passed as arguments.

Possible Workarounds are:
* Make `FooClass.Border` a field and not a property. The bug is only triggered with properties.
* Specify the MemberType explicitely as `{x:Static Border, MemberType={x:Type local:FooClass}}` - this will compile correctly but the designer doesn't like it.

**Comment by walterlv** [comment]
@KodamaSakuno Thanks for your pull request.
