### ISSUE TITLE
TextBox Select Text on Focus Glitch

### ISSUE THREAD

**Issue by KatoFett** [dotnet/wpf#6877]
- .NET Core Version: 5.0
- Does the bug reproduce also in WPF for .NET Framework 4.8?: N/A
- Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No

**Problem description:**
When a textbox receives focus, all of its text should be selected. (See https://stackoverflow.com/questions/660554/how-to-automatically-select-all-text-on-focus-in-wpf-textbox; there is a workaround event attached to PreviewMouseLeftButtonDown which prevents the events from bubbling to controls such as DataGrids for selecting the cell).

**Actual Behavior**
All text gets selected for a moment and is then deselected.

**Expected Behavior**
All text gets selected and stays selected.

**Minimal repro:**

1. Create a WPF project.
2. Put a textbox within the main window that is pre-populated with text
`<TextBox HorizontalAlignment="Left"
                 VerticalAlignment="Top"
                 Text="Select me" />`
3. Register a class handler in the App's OnStartup method that selects all text on focus

        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);
            EventManager.RegisterClassHandler(typeof(TextBox), UIElement.GotFocusEvent, new RoutedEventHandler(TextBox_SelectAllText), true);
        }

        private void TextBox_SelectAllText(object sender, RoutedEventArgs e)
        {
            (sender as TextBox).SelectAll();
        }

4. Run the app and click on the TextBox

**Comment by lindexi** [comment]
@KatoFett How about

```
        private void TextBox_SelectAllText(object sender, RoutedEventArgs e)
        {
            Dispatcher.InvokeAsync(() =>
            {
                (sender as TextBox).SelectAll();
            });
        }
```

See https://github.com/lindexi/lindexi_gd/tree/cce284e03ec7e579b8e584c0ab68a87f8aa91c0a/DikairkacearfairyoWherelewigo

---

Why then deselected? Because the TextBox will update the cursor when mouse up. You can try `SelectAll` in `Dispatcher.InvokeAsync` and then test the step:

1. Download and run my demo code: https://github.com/lindexi/lindexi_gd/tree/cce284e03ec7e579b8e584c0ab68a87f8aa91c0a/DikairkacearfairyoWherelewigo
2. Click the TextBox to focus it by fast mouse down and mouse up.
3. Click the button to make the TextBox lost focus and then click the TextBox to focus it by slow mouse down and mouse up

And you can find the demo code work well when fast click. But the demo code will deselect the TextBox text when slow click.

What is slow click? To be precise, this behavior is not clicking. It means mouse down and wait some time and then mouse up.

**Comment by KatoFett** [comment]
@lindexi Thanks for investigating this.

It works until multiple textboxes are introduced in the XAML and the user goes back and forth between them.

You should be able to see this behavior if you change your XAML to this:

    <StackPanel HorizontalAlignment="Left">
        <TextBox Text="Select Me" />
        <TextBox Text="Select Me" />
    </StackPanel>

And go back and forth between the textboxes.

**Comment by miloush** [comment]
The issue is a bit unclear on whether 
1. it is seeking the default text editor behaviour to be changed so that no code is required
2. it is seeking changes so that the suggested code works as expected
3. is merely asking question on how to achieve the expected behavior

"When a textbox receives focus, all of its text should be selected." is nowhere stated I believe and it is also pretty bad user experience in general, so I am assuming 1. is not the case.

2. would still be a breaking behavior.

The request is underestimating how much is happening when mouse interacts with text boxes, including drag&drop, multiple clicks, extended selection, table resizing, scrolling etc. In order to perform "select all on focus", all these need to be considered and addressed.

Given the circumstances I am assuming a quick dirty solution is acceptable here. The last issue described has not as much to do with multiple TextBoxes as with whether you click inside an existing selection (which starts dragging) or outside (which starts selection). 
@lindexi showed a way to address the outside case and to "fix" the inside case, you can ensure it doesn't happen:

```C#
if (sender is TextBox box)
{
    box.Select(box.SelectionStart, 0); // cancel existing selection
    Dispatcher.InvokeAsync(() => box.SelectAll());
}
```

Obviously this can cause scrolling and you break much of the other interactivity mentioned above, but it sounds like that doesn't matter much for your purposes.

**Comment by KatoFett** [comment]
I'll clarify. We have some textboxes in the app whose values are frequently copied and pasted elsewhere (e.g. email). Our users requested that the text would be automatically selected for those particular textboxes so they could copy all the text easily, so point 3. is what I was going for.

Your solution seems to work consistently and I'm going to close the issue now, thanks!
