### ISSUE TITLE
Setting Label foreground explicity does not work if there are TextBlock Style in one of the merged resource dictionary

### ISSUE THREAD

**Issue by audryste** [dotnet/wpf#7008]
* .NET Core Version:   6.0.8 
* Windows version: 21H1
* Does the bug reproduce also in WPF for .NET Framework 4.8?: **Yes**
 
 
 **Problem description:**
 Cannot change label foreground color when there is textblock style in one of merged dictionary.
   <Label Foreground="Green" Content="This text should be in green"  FontSize="33" />
   
 **Actual behavior:** 
Color is taken in style in texblock from file texts.xaml .

 **Expected behavior:**
Should add label with overriden Green color foreground 

 **Minimal repro:**
[LabelForegroundBug.zip](https://github.com/dotnet/wpf/files/9488634/LabelForegroundBug.zip)

**Comment by audryste** [comment]
Adding bug image for faster bug inspection.
![image](https://user-images.githubusercontent.com/26725810/188420948-65851780-06cb-4a2e-9714-bde865967a43.png)

**Comment by anjalisheel-wpf** [comment]
@audryste A wpf label is a content control. When you set or bind the content of a label to a string then a textblock is created and it's the text of that you are setting.

There's a textblock in the label. Your style sets the foreground of textblock which means it uses that value rather than any other, it would inherit.

You would need the trigger to be on textblock. You're setting foreground on the label. That won't over-ride whatever is set to it.

Start by using a textblock. Then give it a style or set it's style to {x:Null}.

**Comment by miloush** [comment]
Helpful analysis @anjalisheel-wpf! I would add that the resource to point out here is [Dependency property value precedence](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/properties/dependency-property-value-precedence?view=netdesktop-6.0#dependency-property-precedence-list), there you can see that inheritance has a lower precedence than style setters. For troubleshooting, users can use [DependencyPropertyHelper.GetValueSource](https://docs.microsoft.com/en-us/dotnet/api/system.windows.dependencypropertyhelper.getvaluesource?view=windowsdesktop-6.0) (or tools like [Snoop](https://github.com/snoopwpf/snoopwpf)) to find out where a particular value of a property comes from - and this would also reveal that there is actually a TextBlock inside Label.

**Comment by audryste** [comment]
Big thanks @anjalisheel-wpf & @miloush . Now understand the reason. There are similar situations with other components like Grid Header. Is there a way without explicitly setting content to textblock to override textblock style only on this label? I believe Implicit style in parents, should be overridden with implicit style in children. So I tried to override Texblock implicit style in Label. Resources like this:
` <Label Foreground="Green" 
               Content="This text should be in green"  
               FontSize="33">
            <Label.Resources>
                <Style TargetType="{x:Type TextBlock}" 
                       BasedOn="{StaticResource {x:Type TextBlock}}">
                    <Setter Property="Foreground" Value="Yellow"/>
                </Style>
            </Label.Resources>
        </Label>`
However, it did not override the style. It also did not work when the style was in the parent component. It does not matter if the overriding style property means writing some code behind lines.

**Comment by miloush** [comment]
Are you looking for this?
```xml
<Label>
   <TextBlock Text="" />
</Label>
```

**Comment by audryste** [comment]
this means explicitly setting content to textblock. That I wont to avoid. (There is same situation with grid header)

**Comment by audryste** [comment]
Ok to see the idea of the bug, just move style out of merged dictionary to window.resources ... Voila:
![image](https://user-images.githubusercontent.com/26725810/188848521-791ef200-bd36-4722-9350-df4d3a748807.png)

As you see in previous prinstscreen color is different while it should be the same!. If there exists style in merged dictionaries they are not overriden. In children components.

**Comment by audryste** [comment]
Moving textblock style to window.resources will result in different color of label. Thats is the bug. Am I wrong that color should not depend on where style is defined: in merged resources, or component resources?
![image](https://user-images.githubusercontent.com/26725810/188850391-6ce30a25-234c-466b-9fd8-05eb4f37f3d1.png)

**Comment by miloush** [comment]
> Am I wrong that color should not depend on where style is defined: in merged resources, or component resources?

In general yes, that is an incorrect assumption. Already the precedence list gives you a hint of that:

> Implicit styles. Applies only to the [Style](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.style) property. The Style value is any style resource with a [TargetType](https://docs.microsoft.com/en-us/dotnet/api/system.windows.style.targettype) value that matches the element type. **The style resource must exist within the page or application.** Lookup for an implicit style resource doesn't extend to styles resources in Themes.

**Comment by miloush** [comment]
If you put the implicit style in a window, it does not get applied to the `TextBlock` inside `Label`, which only appears as what you want because you only change the color. I am assuming the lookup skips to the application resources, I am checking if I can see why that is the design.

Meanwhile, what is the problem with explicitly setting content on the `Label` as `TextBlock`?

**Comment by miloush** [comment]
Right, so the `TextBlock` is created through `ContentPresenter` and resource lookup does not cross template boundaries. Here is the relevant note:

https://github.com/dotnet/wpf/blob/4dbc072e3f2c30930a7a9ff9dab9114660ae2b88/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FrameworkElement.cs#L901-L907

While there is a `TextBlock` inside `Label`, it is a bit more complicated in practice, it looks more like this:
```
> Label
  > Border
    > ContentPresenter
      > TextBlock
```

If you put a string into content, the `TextBlock` is a template applied to the `ContentPresenter`. That makes the `ContentPresenter` a boundary element and the lookup terminates there. If you put explicit content as `TextBlock`, then there is no need for template hence no boundary and the lookup continues up the tree. 

This means that there is a technical, non-obvious difference between using a string content and `TextBlock` content. None of this really matters to you though, it just explains the behavior you are seeing and that it is by design.

When you look at the precedence list, if you want to override the color, your options are either to use explicit `TextBlock`, or to do considerably more work - custom templates, custom type for the content, new control etc. which I don't see as really necessary.

**Comment by audryste** [comment]
Thousand thanks to @miloush for fully investigating and explaining this issue. Also, for explaining how to use online documentation and tools to navigate caveats like this one.
Also, thank you for looking issue as a user from the human side: "None of this really matters to you though, it just explains the behavior you are seeing and that it is by design." That is 100% true.
Also, for explaining two options to go.
I would really vote against this behavior. Whatever reasons there are for this behavour, a as user the of product I would expect same behavour .
 Is there any procedure or way to offer to vote to change this behavior so that even templated content would behave the same?

**Comment by audryste** [comment]
I wonder... Maybe there is a more simple workaround from the code behind like using DependencyObject.ClearValue or DependencyObject.SetValue?

**Comment by miloush** [comment]
@audryste in general the issue with things like these is that this was the behaviour for the past >15 years and changing it will break existing applications that rely on it. Note that even if the templated and non-templated content behaved the same, neither would allow you to override the color the way you were originally looking for - both have higher precedence than the inherited color from `Label`. I still don't quite understand why you are trying to avoid explicit content, but a custom template might look like this:

```xml
<Style x:Key="TextLabel" TargetType="Label">
    <Setter Property="Template">
        <Setter.Value>
            <ControlTemplate TargetType="Label">
                <TextBlock Text="{TemplateBinding Content}" Foreground="{TemplateBinding Foreground}" />
            </ControlTemplate>
        </Setter.Value>
    </Setter>
</Style>

...

<Label Foreground="Blue" Content="Test" Style="{StaticResource TextLabel}"  />
```

(I am not sure why you need the element to be a `Label` in the first place. Note that if you use any accelerator keys in the content, the `Label` creates `AccessText` rather than `TextBlock` which will not get the implicit `TextBlock` style applied for the same reasons - another potentially unexpected thing to keep in mind.)

**Comment by pchaurasia14** [comment]
@audryste - Does @miloush 's suggested workaround work for you ?
