### ISSUE TITLE
Button content is not rendered correctly in ItemsControl with FlowDirection=RightToLeft

### ISSUE THREAD

**Issue by tephe** [dotnet/wpf#716]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
3.0.100-preview5-011568
* Windows version: (`winver`)
Version 1809 (OS Build 17763.503)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes/No
Yes
 
 
 **Problem description:**
 Very weird behavior that reproduces only when ItemsControl generates a list of buttons with FlowDirection="RightToLeft"
It seems that if the text ends in ")" (closed paranthesis) then this text is appended at the beginning. 

 **Actual behavior:** 

`Button text (content)` on the UI it's shown `)Button (content`
Somehow the same is happening if I insert "\" (backslash) before or after.
`Button (content\\\\)` is rendered `\\\\)Button (content`
`Button (content)\\\\` is rendered `)\\\\Button (content` 

If we change the FlowDirection="LeftToRight" then the button content is rendered correctly.

 **Expected behavior:**

The content to be rendered correctly.
 
 **Minimal repro:**
 
Attached a sample in .NET Core Preview 5 that I used to test this.

[SandBoxWpf.zip](https://github.com/dotnet/wpf/files/3203874/SandBoxWpf.zip)

We actually fixed this issue by using HorizontalAlignment="Right" instead of FlowDirection but the behavior did give us quite a challenge. It seems that even in the Live visual tree the content is OK, only it's rendered incorrectly. Perhaps this is undefined behavior or it hides other issues.

**Comment by weltkante** [comment]
I think thats expected behavior. [FlowDirection](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.flowdirection) is a globalization property and not a layout property, it is inherited across the visual tree. You get the same behavior if you set `FlowDirection="RightToLeft"` on the button outside the `ItemsPresenter`.

The fact that RightToLeft is reversing stack layout is just a side effect, I know some people abuse it for layout purpose, great if it works for them, but the real purpose is for right-to-left writing languages not for layout.

**Comment by tephe** [comment]
Thank you for taking the time to respond, glad it's not a bug 👍 , I'll close the issue now.
