### ISSUE TITLE
Grid columns are not created automatically

### ISSUE THREAD

**Issue by somapatrik** [dotnet/wpf#7262]
* .NET Core Version: 6
* Windows version: 10 21H2
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
 
 **Problem description:**
 If you do not define column definitions inside a grid and only use it, it will not create columns automatically. 

 **Actual behavior:** 
 Used columns (if there is no "Columndefiniton") are stacked on each other.

 **Expected behavior:**
 Used columns should be created automatically using width="*"

 **Minimal repro:**
    
    <Grid>
        <Label Grid.Column="1" 
                   Content="PositionName"/>

        <Label Grid.Column="2"
                   Content="Time"/>
     </Grid>

**Comment by miloush** [comment]
I don't think the documentation claims anywhere that columns should be created this way, so this is more of a feature request rather than a bug. Note that `Grid` without any columns or rows is on extra fast layout path and checking for these cased could have significant performance impact. (It would also be a breaking change to existing applications.)
