### ISSUE TITLE
Port code-generator for WindowsBase\System\Windows\AccessibilitySwitches.cs 

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/wpf#777]
[`WindowsBase\System\Windows\AccessibilitySwitches.cs`](https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/AccessibilitySwitches.cs) is supposed to be generated using a T4 text template. 

This T4 text template is not yet ported to [dotnet/wpf](https://github.com/dotnet/wpf). Port this before RTM => we'll need this for ongoing work, as well as for servicing. 

/cc @rladuca

**Comment by rladuca** [comment]
Not quite sure why we still need this generator.  From my recollection, there was a conversation about no longer needing to guard further accessibility changes with compat flags because:

1. It can complicate changes, especially when flags need to be spread throughout many levels of UIA peers.
2. Self-contained application can ensure they aren't broken by new changes, so the flags aren't really needed.

Are we re-evaluating that decision or am I not correctly recalling what was decided on?

@miguep what are your feelings on the flags since you've been dealing with their proliferation more than I have in the themes?

**Comment by vatsan-madhavan** [comment]
I'd imagine that servicing changes might still need occasional protection. 

It would be rare - for e.g., a security change that everyone wants or needs, but it also creates an unavoidable compatibility regression or behavior changes. I don't think we need to add the T4 generator for this file here - my point is that that's the general case for retaining a reasonably functional quirking infrastructure in place.

**Comment by weltkante** [comment]
> Self-contained application can ensure they aren't broken by new changes, so the flags aren't really needed.

Is definitely not true in general, as soon as you're using third party controls you can't guarantee they'll update the same time as your application. Though I agree the switch from Desktop to Core is a good time to get rid of old compat switches, you'll probably have to reintroduce something in the future when adding new incompatible changes, in order to keep old 3rd party controls running after updates.

**Comment by rladuca** [comment]
Yeah, I'm certainly not arguing that there will never be a need for a compat flag again.  The reason we had that generator is that subsequent releases that made accessibility improvement were forced to be guarded by successive "UseLegacyAccessibility.X" flags.  My point is that, generally, we may not want to expand that set of flags repeatedly as in .NET Framework.

I think we should have this discussion with WinForms folks as well since we used to share the flags.

@merriemcgaw @zsd4yr @Tanya-Solyanik @AdamYoblick What are your plans, going forward, for guarding accessibility changes?  Are you going to keep the status quo of adding new flags per release?

**Comment by rladuca** [comment]
Maybe I am overthinking things, the generator is T4, so it's not like it really takes much effort to copy over.

**Comment by Tanya-Solyanik** [comment]
We had removed our use of accessibility levels. Our assumption is that Core applications requires porting and re-testing, and developers have a chance to workaround any breaking changes that accessibility fixes may bring in. In general the goal for Core is to be an accessible platform out of the box.

**Comment by merriemcgaw** [comment]
We did in fact remove all quirking around accessibility because porting is a complex task for companies and they'll have to rework tests for a variety of reasons. I'm not convinced that we will ever "quirk" accessibility fixes given that Core is SxS. I think our two technologies should work together to have a common story about this.

**Comment by vatsan-madhavan** [comment]
Nice bot :) 

We decided not to do this just yet.
