### ISSUE TITLE
ShowDialog bug on touchscreen c# wpf datagrid

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#7875]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ShowDialog-bug-on-touchscreen-c-wpf-dat/1660656)._

---
[severity:It bothers me. A fix would be nice]
I have:
<DataGrid ItemsSource="{Binding}" AutoGenerateColumns="False">
	<DataGrid.Columns>
		<DataGridTextColumn Header="Имя параметра" IsReadOnly="True" Binding="{Binding Name}" MinWidth="300"/>

<DataGridTemplateColumn Header="Значение" MinWidth="60" IsReadOnly="False">
			<DataGridTemplateColumn.CellTemplate>
				<DataTemplate>
					<TextBlock Text="{Binding Data.Value}" Style="{StaticResource TextBlockCustom}"/>
				</DataTemplate>
			</DataGridTemplateColumn.CellTemplate>
			<DataGridTemplateColumn.CellEditingTemplate>
				<DataTemplate>
					<TextBlock Text="{Binding Data.Value}" Style="{StaticResource TextBlockCustom}">
						<i:Interaction.Triggers>
							<i:EventTrigger EventName="Loaded">
								<i:InvokeCommandAction Command="{Binding ElementName=this, Path=DataContext.Item.CellEditCommand}" CommandParameter="{Binding Data.ID}"/>
							</i:EventTrigger>
							<i:EventTrigger EventName="PreviewMouseLeftButtonDown">
								<i:InvokeCommandAction Command="{Binding ElementName=this, Path=DataContext.Item.CellEditCommand}" CommandParameter="{Binding Data.ID}"/>
							</i:EventTrigger>
						</i:Interaction.Triggers>
					</TextBlock>
				</DataTemplate>
			</DataGridTemplateColumn.CellEditingTemplate>
		</DataGridTemplateColumn>
	</DataGrid.Columns>
</DataGrid>

The code leads to the method:
bool GetNewValue(double aOldValue, out double Result)
            {
                InputWindow inputWindow = new InputWindow(aOldValue);
                
inputWindow.ShowDialog();
                if (inputWindow.DialogResult == true)
                {
                    Result = inputWindow.Value;
                    return true;
                }
                
Result = 0.0;
                return false;
            }

When the previously edited cell is called again, the inputWindow opens, but does not respond to several commands from the touch screen. inputWindow responds immediately to commands from the mouse. I tried replacing the DataGrid with a ListBox, but the result remained the same. For some reason, events from the touch screen are not linked.
The problem is hidden in the operation of the method: . ShowDialog()

---
#### Feedback Bot on 2/11/2022, 07:14 AM: 

(private comment, text removed)
#### Feedback Bot on 6/2/2022, 00:29 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by zokirjanov** [comment]
The issue you are experiencing with the touch screen not responding to commands while the InputWindow is being displayed is likely due to the fact that the ShowDialog() method is a modal operation that runs a separate message loop for the dialog and prevents input from being sent to other windows in the application until the dialog is closed.

To address this issue, you could consider using the non-modal approach to display the InputWindow. Instead of using the ShowDialog() method, you can create an instance of the InputWindow and then call the Show() method to display it. This will allow the InputWindow to be displayed without blocking input to other parts of the application.

Alternatively, you could try handling touch events in a separate thread or using a different approach to handle input events while the InputWindow is displayed.

Here is an example of how you could modify your code to use the non-modal approach:

bool GetNewValue(double aOldValue, out double Result)
{
InputWindow inputWindow = new InputWindow(aOldValue);
inputWindow.Show();

ini
Copy
while (!inputWindow.DialogResult.HasValue)
{
    // Allow other parts of the application to process input
    System.Windows.Forms.Application.DoEvents();
}

if (inputWindow.DialogResult == true)
{
    Result = inputWindow.Value;
    return true;
}

Result = 0.0;
return false;
}

In this example, the InputWindow is displayed using the Show() method and a while loop is used to allow input to be processed by other parts of the application while the InputWindow is open. The loop waits for the DialogResult property of the InputWindow to have a value (i.e., the window has been closed) before continuing. Once the DialogResult is set, the method proceeds with the rest of its logic as before.
