### ISSUE TITLE
Make SaveFileDialog support NOTESTFILECREATE.

### ISSUE THREAD

**Issue by DinoChan** [dotnet/wpf#870]
Needs to stop SaveFileDialog from creating an empty file.

The problem for us is that we have configured the file system security so that a file can be created and filled with data, but once it has been closed, it may not be modified or deleted (by a regular user). When our application tries to use file name returned by the SaveFileDialog, that file already exists and we get the following error when we try to fill it with data: “You don’t have permission to modify files in this network location.”

**Comment by lindexi** [comment]
Because the SaveFileDialog will create a test file to test something and then delete the test file. See [GetSaveFileNameA function (commdlg.h) - Win32 apps | Microsoft Docs](https://docs.microsoft.com/zh-cn/windows/win32/api/commdlg/nf-commdlg-getsavefilenamea ) and [OPENFILENAMEA (commdlg.h) - Win32 apps | Microsoft Docs](https://docs.microsoft.com/zh-cn/windows/win32/api/commdlg/ns-commdlg-openfilenamea )

But the `Options` is get only that we can not set the `OFN_NOTESTFILECREATE` flag.

https://github.com/dotnet/wpf/blob/12601c58ecf03451875395c4adc2adbb3ff243dc/src/Microsoft.DotNet.Wpf/src/PresentationFramework/Microsoft/Win32/FileDialog.cs#L1680-L1689

**Comment by pchaurasia14** [comment]
This enhancement has been implemented in .NET 8. 

Reference - [Link](https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationFramework/Microsoft/Win32/SaveFileDialog.cs#L143-L153)

Hence closing this issue.
