### ISSUE TITLE
[Feature Request] Allow TextBox's line height to be configured

### ISSUE THREAD

**Issue by rampaa** [dotnet/wpf#9867]
Similar to how we can set a [TextBlock's line height](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.textblock.lineheight), if we could configure a TextBox's line height as well, that would be really useful, especially when TextBlock (e.g., https://github.com/dotnet/wpf/issues/9235) and RichTextBox (mainly due to memory and performance related reasons) is not an option.

**Comment by rampaa** [comment]
> `TextBox` already accepts T`extBlock.LineHeight`.

That has some undesired side effects like changing the line height of the context menu as well so I've assumed it wasn't meant to be used for this purpose, did I assume wrong?

TextBox's context menu when `TextBlock.LineHeight` is set to 20:
![image](https://github.com/user-attachments/assets/dd0a7a64-3780-4b69-a472-abf1b8d6393b)

TextBox's context menu when `TextBlock.LineHeight` is set to 50:
![image](https://github.com/user-attachments/assets/a7e2289f-e2bf-42be-9ba4-63d5206d96a1)

**Comment by miloush** [comment]
`TextElement` and `Block` properties are inherited through the tree.

The context menu is not affected by the font size because its default style overrides the inherited font size and explicitly sets it:

https://github.com/dotnet/wpf/blob/0d959af10519bdb23c19cd435611f10bdebe78bf/src/Microsoft.DotNet.Wpf/src/Themes/XAML/ContextMenu.xaml#L17-L24

You could add a style that applies to all context menus and set it back to NaN.

**Comment by rampaa** [comment]
Setting `TextBlock.LineHeight` to `NaN` for `ContextMenu` does solve the issue, thanks! And also thanks for explaining why `TextBlock.LineHeight` affects `ContextMenu` while `FontSize` does not.
