### ISSUE TITLE
Why bindings property dont update view model bindings?

### ISSUE THREAD

**Issue by IlyaNavodkin** [dotnet/wpf#9869]
Hello everyone

I'm trying to create a custom multi-choice combo box with a water message.
I ran into the problem that when binding to the SelectedElementParameterValues property, the FilterItemViewModel view is not updated, although the selection is in control (you can make sure by putting a breakpoint in the window code).
Why is there no binding of the property? Why doesn't it update the viewmodel property? I want to be able to get selected items from the view model.
![image](https://github.com/user-attachments/assets/97219c72-b8a0-4d0d-9192-f61bde6e0170)
![image](https://github.com/user-attachments/assets/f1d607e6-960e-4d75-a703-d35d874c516f)
![image](https://github.com/user-attachments/assets/8d9bb08c-c90a-4d2f-beab-f976720697c1)

Repository with code => https://github.com/IlyaNavodkin/CustomControll

Thank you in advance!

**Comment by miloush** [comment]
Well for start, `SelectedItemsBindable="{Binding SelectedElementParameterValues}"` is invalidated by `SelectedItemsBindable = items`. Then, you do nothing when `SelectedItemsBindable` is set, so even if the binding worked, it wouldn't do anything. It feels like you want the view model to use the selected items that the `MultiSelectComboBox` produces, which you could do with making that binding `Mode=OneWayToSource`. However, that doesn't really work, because the view model expects `ObservableCollection<FilterItemViewModel>` while the selected collection is `ObservableCollection<object>` at best.

If you do the `Mode=OneWayToSource` and change the `FilterItemViewModel.SelectedElementParameterValues` type to `IEnumerable`, it will start working.

However, this is a really complicated and obfuscated way to be doing things. You should have the view model be the source of truth of the selected items collection and make both the cmobo box and the list box use that collection. In that case you would keep the binding as is, but in the `MultiSelectComboBox` class you would need to do something with the collection that you receive, like add to it and remove from it when the selection changes.

**Comment by IlyaNavodkin** [comment]
Thank you for your reply!
I would like my control to work not only with
ObservableCollection<ElementParameterValue>, but with other types of data - for example, inherited from IEnumerable<T> (ObservableCollection<T>, List<T> and more).
Won't it be possible to implement it? Itemssource just works on a similar basis, it accepts collections.

**Comment by miloush** [comment]
Your `MultiSelectComboBox` already uses non-specific collections. You either need it to provide the selected items like `ListBox` does using a read-only property, or you if you want it to also accept external collection of selected items, you need to do something with the value that you receive. If this is intended to be a reusable control, you might want to consider deriving from `MultiSelector` class rather than `UserControl`.

**Comment by IlyaNavodkin** [comment]
If it's not too much trouble, could you enter a code snippet?
I created a component based on MultiSelector, but it does not provide a binding to the SelectedItems property, and if I create a proxy DependencyProperty, it also stops working.

Thank you in advance

**Comment by miloush** [comment]
Can you describe a little bit more what are you trying to achieve? Who do you want to have ownership of the selected data, a viewmodel or your control?

**Comment by IlyaNavodkin** [comment]
I would like the data to be bound to the viewmodel. 
Even if the connection is not two-way.
If you need, I can prepare the project code with model view and control view

**Comment by Nice3point** [comment]
![изображение](https://github.com/user-attachments/assets/ac91f207-5632-483f-a398-f06026a3c5b9)
Bind `IEnumerable` to `IEnumerable`

**Comment by IlyaNavodkin** [comment]
Thx u
